-- Seed questions for all 16 subjects
-- Run with: psql -d adaptive_learning -f seed.sql
-- ELO scale: 10-18 easy | 20-35 medium | 40-70 hard | 80-150 expert

-- ============================================================
-- CALCULUS
-- ============================================================
INSERT INTO calculus (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is the derivative of f(x) = x³?', '3x²', '3x', 'x²', '2x³', '3x²', 'Power rule: d/dx(xⁿ) = nxⁿ⁻¹. So d/dx(x³) = 3x².', 12, 'Calculus'),
('What is the integral of f(x) = 2x?', 'x² + C', '2x² + C', 'x + C', '2 + C', 'x² + C', 'The antiderivative of 2x is x² + C. Verify by differentiating: d/dx(x²) = 2x.', 12, 'Calculus'),
('What is the limit of (sin x)/x as x approaches 0?', '1', '0', 'undefined', 'infinity', '1', 'This is a fundamental limit. As x→0, (sin x)/x → 1. It can be proven using the squeeze theorem.', 14, 'Calculus'),
('What is the derivative of f(x) = e^x?', 'e^x', 'xe^(x-1)', 'e^(x-1)', 'ln(x)', 'e^x', 'The exponential function e^x is its own derivative. This is what makes e special.', 13, 'Calculus'),
('Using the chain rule, what is d/dx[sin(x²)]?', '2x·cos(x²)', 'cos(x²)', '2x·sin(x²)', 'cos(2x)', '2x·cos(x²)', 'Chain rule: d/dx[f(g(x))] = f''(g(x))·g''(x). Here f = sin, g = x², so result is cos(x²)·2x.', 22, 'Calculus'),
('What is the derivative of f(x) = ln(x)?', '1/x', 'x', 'ln(x)/x', 'e^x', '1/x', 'The derivative of the natural log is d/dx[ln(x)] = 1/x for x > 0.', 18, 'Calculus'),
('Evaluate: ∫ x·eˣ dx', 'xe^x - e^x + C', 'xe^x + C', 'e^x + C', 'x²e^x/2 + C', 'xe^x - e^x + C', 'Integration by parts: ∫u·dv = uv - ∫v·du. Let u=x, dv=eˣdx. Then du=dx, v=eˣ. Result: xeˣ - eˣ + C.', 38, 'Calculus'),
('What is the derivative of f(x) = x·sin(x)?', 'sin(x) + x·cos(x)', 'x·cos(x)', 'cos(x)', 'sin(x) - x·cos(x)', 'sin(x) + x·cos(x)', 'Product rule: d/dx[u·v] = u''v + uv''. Here u=x, v=sin(x), so result = sin(x) + x·cos(x).', 25, 'Calculus'),
('Using L''Hôpital''s rule, evaluate lim(x→0) (1 - cos x)/x²', '1/2', '0', '1', 'undefined', '1/2', 'Both numerator and denominator → 0. Apply L''Hôpital twice: (sin x)/(2x) → (cos x)/2 → 1/2.', 45, 'Calculus'),
('What is the Taylor series expansion of e^x around x=0?', '1 + x + x²/2! + x³/3! + ...', '1 + x + x² + x³ + ...', 'x - x³/3! + x⁵/5! - ...', '1 - x²/2! + x⁴/4! - ...', '1 + x + x²/2! + x³/3! + ...', 'The Maclaurin series of eˣ is Σ xⁿ/n! = 1 + x + x²/2! + x³/3! + ... converges for all x.', 65, 'Calculus'),
('Solve the differential equation dy/dx = y, with y(0) = 1', 'y = e^x', 'y = x', 'y = ln(x)', 'y = x²/2', 'y = e^x', 'Separating variables: dy/y = dx → ln|y| = x + C → y = Ae^x. With y(0)=1: A=1, so y=eˣ.', 55, 'Calculus'),
('What does the Fundamental Theorem of Calculus state (Part 1)?', 'If F(x) = ∫ₐˣ f(t)dt, then F''(x) = f(x)', 'Every continuous function has an antiderivative', '∫ₐᵇ f(x)dx = F(b) - F(a)', 'Differentiation and integration are unrelated', 'If F(x) = ∫ₐˣ f(t)dt, then F''(x) = f(x)', 'Part 1 of the FTC states that the derivative of the integral function F(x) = ∫ₐˣ f(t)dt is f(x), connecting differentiation and integration.', 80, 'Calculus');

-- ============================================================
-- DISCRETE MATH
-- ============================================================
INSERT INTO discretemath (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('How many elements are in the power set of a set with 3 elements?', '8', '6', '9', '3', '8', 'The power set of a set with n elements has 2ⁿ elements. For n=3: 2³ = 8.', 12, 'DiscreteMath'),
('What is the result of A ∩ B if A = {1,2,3} and B = {2,3,4}?', '{2,3}', '{1,2,3,4}', '{1,4}', '{1,2,3}', '{2,3}', 'Intersection (∩) contains only elements in BOTH sets. A and B share 2 and 3.', 12, 'DiscreteMath'),
('In propositional logic, what is the truth value of "P AND (NOT P)"?', 'Always false', 'Always true', 'Depends on P', 'Undefined', 'Always false', 'P ∧ ¬P is a contradiction — it is always false regardless of the truth value of P.', 14, 'DiscreteMath'),
('How many ways can you choose 3 items from 7 distinct items (order doesn''t matter)?', '35', '21', '210', '42', '35', 'Combination formula: C(7,3) = 7!/(3!·4!) = 35. Order doesn''t matter, so we use combinations.', 22, 'DiscreteMath'),
('What is the base case for proving by induction that 1+2+...+n = n(n+1)/2?', 'n=1: 1 = 1(2)/2 = 1 ✓', 'n=0: 0 = 0', 'n=2: 3 = 2(3)/2 ✓', 'n=1: 1 = 1²', 'n=1: 1 = 1(2)/2 = 1 ✓', 'For mathematical induction, the base case n=1 gives: LHS=1, RHS=1(1+1)/2=1. Both sides equal 1, so base case holds.', 28, 'DiscreteMath'),
('In a simple graph with 5 vertices, what is the maximum number of edges?', '10', '5', '20', '15', '10', 'A complete graph Kₙ has n(n-1)/2 edges. For n=5: 5(4)/2 = 10.', 35, 'DiscreteMath'),
('What recurrence relation describes the Fibonacci sequence?', 'F(n) = F(n-1) + F(n-2)', 'F(n) = 2·F(n-1)', 'F(n) = F(n-1)·F(n-2)', 'F(n) = F(n-1) + n', 'F(n) = F(n-1) + F(n-2)', 'Fibonacci: each term is the sum of the two preceding terms. F(1)=1, F(2)=1, F(n)=F(n-1)+F(n-2).', 30, 'DiscreteMath'),
('What is the chromatic number of a complete graph K₄?', '4', '3', '6', '2', '4', 'In K₄ every vertex connects to every other vertex. No two adjacent vertices can share a color, so you need 4 distinct colors.', 55, 'DiscreteMath'),
('Which problem is NP-complete?', 'Boolean satisfiability (SAT)', 'Sorting a list', 'Finding shortest path', 'Binary search', 'Boolean satisfiability (SAT)', 'SAT was the first problem proven NP-complete (Cook''s theorem, 1971). Many other NP-complete problems are reduced from SAT.', 85, 'DiscreteMath'),
('What does Euler''s formula V - E + F = 2 apply to?', 'Connected planar graphs', 'All graphs', 'Trees only', 'Bipartite graphs', 'Connected planar graphs', 'Euler''s formula V-E+F=2 holds for any connected planar graph, where V=vertices, E=edges, F=faces (including the outer face).', 70, 'DiscreteMath');

-- ============================================================
-- LINEAR ALGEBRA
-- ============================================================
INSERT INTO linearalgebra (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is the dot product of vectors (1,2) and (3,4)?', '11', '5', '7', '14', '11', 'Dot product: (1)(3) + (2)(4) = 3 + 8 = 11.', 12, 'LinearAlgebra'),
('What is the determinant of the 2×2 matrix [[1,2],[3,4]]?', '-2', '2', '-10', '10', '-2', 'For [[a,b],[c,d]], det = ad - bc = (1)(4) - (2)(3) = 4 - 6 = -2.', 15, 'LinearAlgebra'),
('A matrix multiplied by its inverse equals which matrix?', 'The identity matrix', 'The zero matrix', 'The transpose', 'The original matrix', 'The identity matrix', 'By definition, A·A⁻¹ = I, where I is the identity matrix (1s on diagonal, 0s elsewhere).', 18, 'LinearAlgebra'),
('If λ is an eigenvalue of matrix A with eigenvector v, which equation holds?', 'Av = λv', 'Av = v/λ', 'A + v = λ', 'det(A) = λ', 'Av = λv', 'The eigenvalue equation is Av = λv: multiplying A by eigenvector v just scales v by the eigenvalue λ.', 30, 'LinearAlgebra'),
('What is the rank of a matrix?', 'The number of linearly independent rows (or columns)', 'The number of rows', 'The determinant', 'The trace', 'The number of linearly independent rows (or columns)', 'Rank = dimension of the column space = number of linearly independent rows = number of pivots in row echelon form.', 32, 'LinearAlgebra'),
('What does it mean for a set of vectors to be linearly independent?', 'No vector can be written as a linear combination of the others', 'All vectors are unit vectors', 'All vectors are orthogonal', 'The vectors span all of Rⁿ', 'No vector can be written as a linear combination of the others', 'Linear independence means c₁v₁ + c₂v₂ + ... = 0 implies all cᵢ = 0. No vector is "redundant".', 35, 'LinearAlgebra'),
('What is the trace of the matrix [[3,1],[2,4]]?', '7', '10', '5', '-2', '7', 'The trace is the sum of diagonal elements: 3 + 4 = 7.', 22, 'LinearAlgebra'),
('In Gram-Schmidt orthogonalization, what is the goal?', 'Convert a basis into an orthonormal basis', 'Find eigenvalues', 'Invert a matrix', 'Compute the determinant', 'Convert a basis into an orthonormal basis', 'Gram-Schmidt takes a set of linearly independent vectors and produces an orthonormal set spanning the same subspace.', 50, 'LinearAlgebra'),
('What does the singular value decomposition (SVD) of a matrix A yield?', 'A = UΣVᵀ where U,V are orthogonal and Σ is diagonal', 'A = LU where L is lower triangular', 'A = QR where Q is orthogonal', 'A = PDP⁻¹ where D is diagonal', 'A = UΣVᵀ where U,V are orthogonal and Σ is diagonal', 'SVD decomposes any m×n matrix as A=UΣVᵀ. The diagonal entries of Σ are singular values. Fundamental in data science/PCA.', 90, 'LinearAlgebra'),
('If Ax = b has no solution, the least-squares solution minimises which quantity?', '||Ax - b||²', '||x||²', 'det(A)', 'trace(A)', '||Ax - b||²', 'The least-squares solution x̂ = (AᵀA)⁻¹Aᵀb minimises the squared residual ||Ax-b||², finding the best approximate solution.', 75, 'LinearAlgebra');

-- ============================================================
-- STATISTICS
-- ============================================================
INSERT INTO statistics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is the mean of the dataset {2, 4, 6, 8, 10}?', '6', '5', '7', '8', '6', 'Mean = (2+4+6+8+10)/5 = 30/5 = 6.', 11, 'Statistics'),
('What is the probability of rolling a 6 on a fair die?', '1/6', '1/3', '1/2', '1/4', '1/6', 'A fair die has 6 equally likely outcomes. P(rolling 6) = 1/6 ≈ 0.167.', 11, 'Statistics'),
('For independent events A and B, P(A and B) equals what?', 'P(A) × P(B)', 'P(A) + P(B)', 'P(A) + P(B) - P(A or B)', 'P(A|B)', 'P(A) × P(B)', 'For independent events, knowing B gives no information about A, so P(A∩B) = P(A)·P(B).', 18, 'Statistics'),
('What does standard deviation measure?', 'How spread out values are from the mean', 'The middle value in a dataset', 'The most frequent value', 'The range of a dataset', 'How spread out values are from the mean', 'Standard deviation is the square root of variance. Small SD = data clustered near mean; large SD = data widely spread.', 17, 'Statistics'),
('In a normal distribution, approximately what percentage of data falls within 1 standard deviation of the mean?', '68%', '95%', '99.7%', '50%', '68%', 'The empirical rule: ~68% within 1σ, ~95% within 2σ, ~99.7% within 3σ of the mean.', 25, 'Statistics'),
('What is Bayes'' theorem?', 'P(A|B) = P(B|A)·P(A) / P(B)', 'P(A|B) = P(A) + P(B)', 'P(A|B) = P(A) / P(B)', 'P(A|B) = P(B|A)', 'P(A|B) = P(B|A)·P(A) / P(B)', 'Bayes'' theorem updates probability based on new evidence. P(A|B) = P(B|A)·P(A)/P(B) where P(A) is the prior.', 40, 'Statistics'),
('In hypothesis testing, what does a p-value represent?', 'Probability of observing results this extreme assuming H₀ is true', 'Probability that H₀ is true', 'Probability that H₁ is true', 'The significance level', 'Probability of observing results this extreme assuming H₀ is true', 'The p-value is the probability of obtaining a test statistic at least as extreme as observed, assuming the null hypothesis is true.', 45, 'Statistics'),
('What is the Central Limit Theorem?', 'Sample means approach a normal distribution as sample size increases', 'All populations are normally distributed', 'Large samples always have small variance', 'The mean equals the median for all distributions', 'Sample means approach a normal distribution as sample size increases', 'CLT: regardless of population distribution, the distribution of sample means approaches N(μ, σ²/n) as n → ∞.', 55, 'Statistics'),
('What does maximum likelihood estimation (MLE) do?', 'Finds parameters that maximise the probability of observed data', 'Minimises the sum of squared errors', 'Finds the median of the posterior distribution', 'Minimises the number of parameters', 'Finds parameters that maximise the probability of observed data', 'MLE finds θ̂ = argmax L(θ|data) where L is the likelihood function — the parameter values under which the data is most probable.', 80, 'Statistics'),
('What distinguishes a Type I error from a Type II error?', 'Type I: rejecting a true H₀. Type II: failing to reject a false H₀', 'Type I: accepting H₁. Type II: accepting H₀', 'Type I: small sample error. Type II: large sample error', 'Type I is worse than Type II always', 'Type I: rejecting a true H₀. Type II: failing to reject a false H₀', 'Type I error (false positive) = α = significance level. Type II error (false negative) = β. Power = 1 - β.', 50, 'Statistics');

-- ============================================================
-- ANATOMY
-- ============================================================
INSERT INTO anatomy (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('How many chambers does the human heart have?', '4', '2', '3', '6', '4', 'The heart has 4 chambers: right atrium, right ventricle, left atrium, and left ventricle.', 11, 'Anatomy'),
('Which bone is the longest in the human body?', 'Femur', 'Humerus', 'Tibia', 'Fibula', 'Femur', 'The femur (thigh bone) is the longest, strongest bone in the body, running from the hip to the knee.', 11, 'Anatomy'),
('Which lobe of the brain is primarily responsible for vision?', 'Occipital lobe', 'Frontal lobe', 'Parietal lobe', 'Temporal lobe', 'Occipital lobe', 'The occipital lobe, at the back of the brain, contains the primary visual cortex and processes visual information.', 16, 'Anatomy'),
('What is the anatomical term for the palm-side of the hand?', 'Palmar', 'Dorsal', 'Lateral', 'Medial', 'Palmar', 'Palmar (or volar) refers to the anterior surface of the hand. Dorsal refers to the back of the hand.', 17, 'Anatomy'),
('How many cranial nerves are there in the human nervous system?', '12', '10', '8', '14', '12', 'There are 12 pairs of cranial nerves (CN I–XII), emerging directly from the brain and brainstem, not the spinal cord.', 25, 'Anatomy'),
('The mitral valve is located between which two heart chambers?', 'Left atrium and left ventricle', 'Right atrium and right ventricle', 'Left ventricle and aorta', 'Right ventricle and pulmonary artery', 'Left atrium and left ventricle', 'The mitral (bicuspid) valve controls blood flow from the left atrium to the left ventricle. The tricuspid valve is on the right side.', 30, 'Anatomy'),
('Which structure passes through the carpal tunnel?', 'Median nerve', 'Ulnar nerve', 'Radial nerve', 'Axillary nerve', 'Median nerve', 'The carpal tunnel contains the median nerve and 9 flexor tendons. Compression causes carpal tunnel syndrome.', 42, 'Anatomy'),
('The Circle of Willis is a structure found where in the body?', 'Base of the brain', 'Heart', 'Kidney', 'Liver', 'Base of the brain', 'The Circle of Willis is an arterial circle at the base of the brain connecting the carotid and vertebrobasilar systems, providing collateral blood flow.', 55, 'Anatomy'),
('What is the name of the tough outer membrane that surrounds the brain?', 'Dura mater', 'Arachnoid mater', 'Pia mater', 'Periosteum', 'Dura mater', 'The dura mater is the outermost of the three meninges. Deep to it: arachnoid mater, then pia mater (touching the brain surface).', 45, 'Anatomy'),
('Where does lymphatic drainage from the right arm and right side of the thorax ultimately drain into?', 'Right subclavian vein', 'Left subclavian vein', 'Superior vena cava', 'Right jugular vein', 'Right subclavian vein', 'The right lymphatic duct drains into the right subclavian vein. The thoracic duct (left side) drains everything else into the left subclavian vein.', 75, 'Anatomy');

-- ============================================================
-- MICROBIOLOGY
-- ============================================================
INSERT INTO microbiology (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What does Gram staining differentiate?', 'Bacteria with thick vs thin peptidoglycan cell walls', 'Viruses from bacteria', 'Aerobic from anaerobic bacteria', 'Spore-forming from non-spore-forming bacteria', 'Bacteria with thick vs thin peptidoglycan cell walls', 'Gram-positive bacteria retain crystal violet (appear purple) due to thick peptidoglycan. Gram-negative bacteria lose it and stain pink with safranin.', 12, 'Microbiology'),
('What is binary fission?', 'Asexual reproduction by splitting into two cells', 'Sexual reproduction in bacteria', 'A form of budding', 'Viral replication', 'Asexual reproduction by splitting into two cells', 'Binary fission is how most bacteria reproduce: the cell duplicates its DNA, grows, and divides into two identical daughter cells.', 12, 'Microbiology'),
('Which type of RNA carries amino acids to the ribosome during translation?', 'tRNA (transfer RNA)', 'mRNA (messenger RNA)', 'rRNA (ribosomal RNA)', 'snRNA', 'tRNA (transfer RNA)', 'tRNA has an anticodon that matches mRNA codons and carries the corresponding amino acid to the ribosome for protein synthesis.', 20, 'Microbiology'),
('What is the lytic cycle in bacteriophage replication?', 'Phage replicates and lyses the host cell', 'Phage DNA integrates into host chromosome', 'Host cell becomes dormant', 'Phage exits without killing the host', 'Phage replicates and lyses the host cell', 'In the lytic cycle: phage injects DNA → host replicates phage → new phages lyse the cell. Contrast with lysogenic cycle where phage DNA integrates.', 28, 'Microbiology'),
('What mechanism do bacteria use to become resistant to beta-lactam antibiotics?', 'Producing beta-lactamase enzymes', 'Increasing membrane permeability', 'Decreasing ribosome number', 'Changing their DNA sequence randomly', 'Producing beta-lactamase enzymes', 'Beta-lactamase cleaves the beta-lactam ring of antibiotics like penicillin, inactivating them. MRSA uses an altered penicillin-binding protein instead.', 45, 'Microbiology'),
('What is a biofilm?', 'A structured community of bacteria embedded in a self-produced matrix', 'A thin film of viral particles', 'A bacterial toxin layer', 'A laboratory growth medium', 'A structured community of bacteria embedded in a self-produced matrix', 'Biofilms form on surfaces and medical devices. Bacteria in biofilms are up to 1000× more resistant to antibiotics than planktonic cells.', 50, 'Microbiology'),
('What is horizontal gene transfer?', 'Transfer of genes between organisms in the same generation', 'Gene transfer from parent to offspring', 'Mutation caused by radiation', 'Gene expression regulation', 'Transfer of genes between organisms in the same generation', 'HGT occurs via conjugation (plasmid transfer), transformation (uptake of free DNA), or transduction (phage-mediated). Key driver of antibiotic resistance spread.', 70, 'Microbiology'),
('What is the mechanism of action of CRISPR-Cas9?', 'Guide RNA directs Cas9 nuclease to cut specific DNA sequences', 'Cas9 methylates target DNA', 'Guide RNA blocks gene transcription', 'Cas9 inserts random mutations', 'Guide RNA directs Cas9 nuclease to cut specific DNA sequences', 'CRISPR-Cas9: sgRNA (guide RNA) hybridises to target DNA, directing Cas9 to make a double-strand break. The cell repairs it, enabling gene editing.', 90, 'Microbiology'),
('Which bacterial structure protects against phagocytosis?', 'Capsule', 'Flagellum', 'Pilus', 'Ribosome', 'Capsule', 'The polysaccharide capsule prevents opsonisation and phagocytosis by macrophages. Encapsulated bacteria (e.g. S. pneumoniae) are more virulent.', 38, 'Microbiology'),
('What is quorum sensing?', 'Cell-density-dependent gene regulation via signalling molecules', 'Bacterial response to temperature', 'Synchronised cell division', 'Nutrient-sensing pathway', 'Cell-density-dependent gene regulation via signalling molecules', 'Bacteria secrete autoinducers that accumulate with population density. Once a threshold is reached, coordinated behaviours (biofilm, virulence) are triggered.', 65, 'Microbiology');

-- ============================================================
-- MOLECULAR BIOLOGY
-- ============================================================
INSERT INTO molecularbiology (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What are the four bases found in DNA?', 'Adenine, Thymine, Guanine, Cytosine', 'Adenine, Uracil, Guanine, Cytosine', 'Adenine, Thymine, Guanine, Uracil', 'Adenine, Thymine, Cytosine, Serine', 'Adenine, Thymine, Guanine, Cytosine', 'DNA contains A, T, G, C. RNA replaces Thymine with Uracil. Base pairing: A-T (2 H-bonds), G-C (3 H-bonds).', 11, 'MolecularBiology'),
('What enzyme synthesises a new DNA strand during replication?', 'DNA polymerase', 'RNA polymerase', 'Helicase', 'Ligase', 'DNA polymerase', 'DNA polymerase extends the new strand by adding nucleotides complementary to the template (5''→3'' direction). It needs a primer to start.', 13, 'MolecularBiology'),
('What is the central dogma of molecular biology?', 'DNA → RNA → Protein', 'RNA → DNA → Protein', 'Protein → RNA → DNA', 'DNA → Protein → RNA', 'DNA → RNA → Protein', 'The central dogma: DNA is transcribed to mRNA, which is translated into protein. Reverse transcriptase (retroviruses) can go RNA→DNA.', 14, 'MolecularBiology'),
('What is the role of a promoter in gene expression?', 'It is a DNA sequence where RNA polymerase binds to initiate transcription', 'It increases translation speed', 'It stabilises mRNA', 'It codes for a regulatory protein', 'It is a DNA sequence where RNA polymerase binds to initiate transcription', 'Promoters (e.g. TATA box) are upstream of genes. Transcription factors bind the promoter to recruit RNA polymerase and initiate transcription.', 25, 'MolecularBiology'),
('What is alternative splicing?', 'Different combinations of exons are joined to produce multiple proteins from one gene', 'Introns are retained in mature mRNA', 'DNA is spliced into the chromosome', 'Different genes are transcribed together', 'Different combinations of exons are joined to produce multiple proteins from one gene', 'Alternative splicing allows one gene to produce multiple protein isoforms. ~95% of human multi-exon genes are alternatively spliced.', 40, 'MolecularBiology'),
('What is the function of telomerase?', 'It extends telomeres at chromosome ends to prevent shortening', 'It repairs double-strand breaks', 'It methylates DNA', 'It removes RNA primers', 'It extends telomeres at chromosome ends to prevent shortening', 'Without telomerase, chromosomes shorten with each division. Telomerase adds TTAGGG repeats. It is active in stem cells and cancer cells.', 55, 'MolecularBiology'),
('What is epigenetic modification?', 'Heritable changes in gene expression without altering the DNA sequence', 'Mutations in the coding sequence', 'Changes in protein folding', 'Recombination during meiosis', 'Heritable changes in gene expression without altering the DNA sequence', 'Epigenetics includes DNA methylation (gene silencing) and histone modification (chromatin remodelling). These are heritable through cell division.', 60, 'MolecularBiology'),
('What is a missense mutation?', 'A nucleotide change that results in a different amino acid', 'A mutation that creates a stop codon', 'Deletion of a single nucleotide', 'Insertion of extra nucleotides', 'A nucleotide change that results in a different amino acid', 'Missense: codon changes to specify a different amino acid. Contrast: nonsense (stop codon), silent (same amino acid), frameshift (reading frame shift).', 35, 'MolecularBiology'),
('What is the role of chaperone proteins?', 'They assist in correct protein folding and prevent aggregation', 'They degrade misfolded proteins', 'They transport proteins across membranes', 'They regulate gene transcription', 'They assist in correct protein folding and prevent aggregation', 'Chaperones (e.g. HSP70) bind unfolded proteins, preventing inappropriate interactions and allowing correct folding. Important under stress conditions.', 70, 'MolecularBiology'),
('What is the significance of the Shine-Dalgarno sequence in bacteria?', 'It is an mRNA sequence that aligns the ribosome for translation initiation', 'It is a DNA regulatory element', 'It marks the end of a gene', 'It codes for the start methionine', 'It is an mRNA sequence that aligns the ribosome for translation initiation', 'The Shine-Dalgarno sequence (5''-AGGAGG-3'') is complementary to the 16S rRNA. It positions the ribosome at the start codon (AUG) in prokaryotes.', 85, 'MolecularBiology');

-- ============================================================
-- PHYSIOLOGY
-- ============================================================
INSERT INTO physiology (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is cardiac output?', 'Heart rate × stroke volume', 'Systolic pressure × heart rate', 'Blood volume / time', 'Heart rate / stroke volume', 'Heart rate × stroke volume', 'CO = HR × SV. A resting HR of 70 bpm × SV of 70 mL = ~4.9 L/min. Increases dramatically during exercise.', 13, 'Physiology'),
('Which ion is responsible for triggering the action potential in neurons?', 'Sodium (Na⁺)', 'Potassium (K⁺)', 'Calcium (Ca²⁺)', 'Chloride (Cl⁻)', 'Sodium (Na⁺)', 'During depolarisation, voltage-gated Na⁺ channels open and Na⁺ rushes into the cell, raising membrane potential from -70mV toward +30mV.', 15, 'Physiology'),
('What is the primary function of the kidney''s glomerulus?', 'Filtration of blood plasma', 'Reabsorption of glucose', 'Secretion of hydrogen ions', 'Concentration of urine', 'Filtration of blood plasma', 'The glomerulus is a capillary network in the Bowman''s capsule. High pressure forces plasma (minus large proteins) into the tubule at ~180L/day.', 20, 'Physiology'),
('What does the Frank-Starling law of the heart describe?', 'Increased ventricular filling leads to increased stroke volume', 'Heart rate decreases when blood pressure rises', 'Cardiac output is constant regardless of filling', 'Stroke volume decreases with exercise', 'Increased ventricular filling leads to increased stroke volume', 'Frank-Starling: the more the ventricle is stretched (preload), the stronger the contraction and the greater the stroke volume. Automatic output matching.', 38, 'Physiology'),
('What is the Henderson-Hasselbalch equation used for?', 'Calculating blood pH from bicarbonate and CO₂ levels', 'Calculating cardiac output', 'Measuring renal clearance', 'Determining lung compliance', 'Calculating blood pH from bicarbonate and CO₂ levels', 'pH = pKa + log([HCO₃⁻]/[H₂CO₃]). Normal pH = 6.1 + log(24/1.2) = 7.4. Essential for acid-base analysis.', 50, 'Physiology'),
('During exercise, how does the oxygen-haemoglobin dissociation curve shift?', 'Right shift (Bohr effect) — favouring O₂ release to tissues', 'Left shift — favouring O₂ binding', 'No shift', 'Vertical shift', 'Right shift (Bohr effect) — favouring O₂ release to tissues', 'Exercise raises CO₂, temperature, and 2,3-DPG, decreasing haemoglobin''s O₂ affinity. The curve shifts right, releasing more O₂ to working muscles.', 55, 'Physiology'),
('What is the primary mechanism of countercurrent multiplication in the kidney?', 'Active NaCl transport out of the ascending loop creates an osmotic gradient', 'Water is pumped out of the descending loop', 'Urea is concentrated in the cortex', 'ADH drives active transport of water', 'Active NaCl transport out of the ascending loop creates an osmotic gradient', 'The thick ascending limb pumps NaCl into the medullary interstitium (impermeably to water), creating hyperosmolarity that concentrates urine in the collecting duct.', 75, 'Physiology'),
('What causes the QRS complex on an ECG?', 'Ventricular depolarisation', 'Atrial depolarisation', 'Ventricular repolarisation', 'Atrial repolarisation', 'Ventricular depolarisation', 'P wave = atrial depolarisation. QRS = ventricular depolarisation (largest because ventricles are biggest). T wave = ventricular repolarisation.', 35, 'Physiology'),
('Which hormone primarily regulates blood calcium levels?', 'Parathyroid hormone (PTH)', 'Insulin', 'Cortisol', 'ADH', 'Parathyroid hormone (PTH)', 'PTH is released when Ca²⁺ drops. It increases Ca²⁺ by: bone resorption, renal Ca²⁺ reabsorption, and activating vitamin D (gut absorption).', 42, 'Physiology'),
('What is the pulmonary capillary wedge pressure (PCWP) an estimate of?', 'Left atrial pressure', 'Right atrial pressure', 'Pulmonary artery pressure', 'Aortic pressure', 'Left atrial pressure', 'PCWP is measured by wedging a catheter in a pulmonary artery. With flow stopped, it equilibrates with left atrial pressure — a key measure of left heart function.', 90, 'Physiology');

-- ============================================================
-- ANALYTICAL CHEMISTRY
-- ============================================================
INSERT INTO analyticalchemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is the pH of a solution with [H⁺] = 1×10⁻⁷ M?', '7', '3', '11', '14', '7', 'pH = -log[H⁺] = -log(10⁻⁷) = 7. This is neutral pH at 25°C (pure water).', 12, 'AnalyticalChemistry'),
('In a titration, what is the equivalence point?', 'The point where moles of titrant exactly equal moles of analyte', 'The point of maximum indicator colour change', 'The midpoint of the titration', 'The point where pH = 7', 'The point where moles of titrant exactly equal moles of analyte', 'At the equivalence point, stoichiometric amounts of acid and base have reacted completely. The endpoint (indicator colour change) approximates this.', 15, 'AnalyticalChemistry'),
('What does Beer-Lambert law relate?', 'Absorbance to concentration and path length (A = εlc)', 'Wavelength to photon energy', 'pH to concentration', 'Refractive index to concentration', 'Absorbance to concentration and path length (A = εlc)', 'A = εlc where ε = molar absorptivity, l = path length (cm), c = concentration (mol/L). Basis of spectrophotometry.', 25, 'AnalyticalChemistry'),
('What is the stationary phase in gas chromatography (GC)?', 'A non-volatile liquid coating inside the column', 'The carrier gas', 'The sample injected', 'The detector', 'A non-volatile liquid coating inside the column', 'In GC, the stationary phase is a high-boiling liquid coated on the column. The mobile phase is an inert carrier gas (He, N₂). Separation is by volatility/polarity.', 32, 'AnalyticalChemistry'),
('What does a mass spectrometer measure?', 'The mass-to-charge ratio (m/z) of ions', 'Absorbance at UV wavelengths', 'The pKa of a compound', 'Electrochemical potential', 'The mass-to-charge ratio (m/z) of ions', 'Mass spec ionises molecules, separates ions by m/z, and detects them. The molecular ion peak gives molecular weight; fragmentation pattern gives structure.', 45, 'AnalyticalChemistry'),
('In ¹H NMR spectroscopy, what does chemical shift (δ) indicate?', 'The electronic environment of a proton', 'The number of protons', 'Coupling between protons', 'The molecular weight', 'The electronic environment of a proton', 'Chemical shift reflects electron density around a proton. Deshielded protons (near electronegative groups) have higher δ (downfield). Referenced to TMS at 0 ppm.', 55, 'AnalyticalChemistry'),
('What is the principle behind inductively coupled plasma mass spectrometry (ICP-MS)?', 'Sample is atomised in argon plasma, ions are separated by m/z for elemental analysis', 'Sample absorbs UV light proportional to concentration', 'Sample reacts with reagents to produce coloured product', 'Ions migrate in an electric field based on size', 'Sample is atomised in argon plasma, ions are separated by m/z for elemental analysis', 'ICP-MS: plasma (6000-8000K) atomises and ionises the sample. Ions enter the mass spectrometer and are detected by m/z. Detects elements at parts-per-trillion levels.', 80, 'AnalyticalChemistry'),
('What is Karl Fischer titration used to measure?', 'Water content in a sample', 'Acid content', 'Metal ion concentration', 'Dissolved oxygen', 'Water content in a sample', 'Karl Fischer titration specifically measures water content. It uses iodine, SO₂, pyridine (or imidazole), and methanol. The reaction stoichiometrically consumes water.', 60, 'AnalyticalChemistry'),
('What is a buffer solution?', 'A solution that resists pH change when acid or base is added', 'A solution of known pH', 'A neutral (pH 7) solution', 'A saturated salt solution', 'A solution that resists pH change when acid or base is added', 'A buffer contains a weak acid and its conjugate base (or weak base/conjugate acid). It works best when pH ≈ pKa (Henderson-Hasselbalch equation).', 22, 'AnalyticalChemistry'),
('What is the detection limit in analytical chemistry?', 'The lowest concentration reliably distinguished from blank signal', 'The highest concentration measurable', 'The concentration giving 100% recovery', 'The precision of repeated measurements', 'The lowest concentration reliably distinguished from blank signal', 'LOD = 3σ/slope of calibration, where σ is the standard deviation of blank measurements. The limit of quantification (LOQ) is typically 10σ/slope.', 70, 'AnalyticalChemistry');

-- ============================================================
-- BIOCHEMISTRY
-- ============================================================
INSERT INTO biochemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What type of bond links amino acids in a protein?', 'Peptide bond', 'Hydrogen bond', 'Ionic bond', 'Disulfide bond', 'Peptide bond', 'A peptide bond forms between the carboxyl group of one amino acid and the amino group of the next, releasing water (condensation reaction).', 12, 'Biochemistry'),
('What is the first step of glycolysis?', 'Phosphorylation of glucose to glucose-6-phosphate', 'Conversion of pyruvate to acetyl-CoA', 'Production of NADH', 'Cleavage of fructose-1,6-bisphosphate', 'Phosphorylation of glucose to glucose-6-phosphate', 'Hexokinase phosphorylates glucose using ATP → glucose-6-phosphate. This traps glucose in the cell (can''t cross membrane) and commits it to glycolysis.', 18, 'Biochemistry'),
('What is the net ATP yield from one glucose molecule in glycolysis?', '2 ATP', '36 ATP', '4 ATP', '1 ATP', '2 ATP', 'Glycolysis produces 4 ATP but uses 2, giving a net of 2 ATP per glucose. It also produces 2 NADH and 2 pyruvate.', 18, 'Biochemistry'),
('What is the role of coenzyme A (CoA) in metabolism?', 'It carries acyl groups (like acetyl) to metabolic reactions', 'It transfers phosphate groups', 'It donates electrons in the electron transport chain', 'It catalyses oxidation reactions directly', 'It carries acyl groups (like acetyl) to metabolic reactions', 'CoA has a thiol (-SH) group that forms a high-energy thioester bond with acetyl groups. Acetyl-CoA enters the Krebs cycle and is key for fatty acid metabolism.', 32, 'Biochemistry'),
('What is the Michaelis constant (Km) a measure of?', 'The substrate concentration at which reaction rate is half-maximal', 'Maximum reaction velocity', 'Enzyme concentration', 'Product inhibition strength', 'The substrate concentration at which reaction rate is half-maximal', 'Km = [S] when V = Vmax/2. Low Km = high enzyme affinity for substrate. Derived from the Michaelis-Menten equation: V = Vmax[S]/(Km + [S]).', 45, 'Biochemistry'),
('Where does the electron transport chain occur in eukaryotic cells?', 'Inner mitochondrial membrane', 'Outer mitochondrial membrane', 'Cytoplasm', 'Nucleus', 'Inner mitochondrial membrane', 'Complexes I-IV are embedded in the inner mitochondrial membrane. They use NADH/FADH₂ from the Krebs cycle to pump protons, driving ATP synthase.', 38, 'Biochemistry'),
('What is the function of ubiquitin?', 'It tags proteins for proteasomal degradation', 'It activates transcription', 'It transports oxygen', 'It catalyses ATP hydrolysis', 'It tags proteins for proteasomal degradation', 'Ubiquitin is a small protein that is covalently attached to target proteins. Polyubiquitination signals the 26S proteasome to degrade the protein.', 55, 'Biochemistry'),
('What is feedback inhibition?', 'A metabolic pathway''s end product inhibits an early enzyme in the pathway', 'Substrate inhibits its own enzyme', 'Product activates its biosynthetic enzyme', 'A hormone inhibits cellular metabolism', 'A metabolic pathway''s end product inhibits an early enzyme in the pathway', 'Classic example: isoleucine inhibits threonine deaminase (first enzyme in its synthesis). This prevents overproduction — an elegant regulatory mechanism.', 42, 'Biochemistry'),
('What is the primary structure of a protein?', 'The amino acid sequence', 'Alpha helices and beta sheets', 'The 3D folded shape', 'Quaternary assembly of subunits', 'The amino acid sequence', 'The four levels: primary (sequence), secondary (local folding: helices/sheets), tertiary (overall 3D fold), quaternary (multi-subunit assembly).', 15, 'Biochemistry'),
('What role does FAD play in the Krebs cycle?', 'It accepts electrons (is reduced to FADH₂) in the succinate dehydrogenase reaction', 'It donates electrons to NAD⁺', 'It transfers acetyl groups', 'It hydrolyses GTP', 'It accepts electrons (is reduced to FADH₂) in the succinate dehydrogenase reaction', 'Succinate dehydrogenase converts succinate → fumarate and reduces FAD to FADH₂. FADH₂ then donates electrons to Complex II of the electron transport chain.', 60, 'Biochemistry');

-- ============================================================
-- INORGANIC CHEMISTRY
-- ============================================================
INSERT INTO inorganicchemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('In the periodic table, which group contains the alkali metals?', 'Group 1', 'Group 2', 'Group 17', 'Group 18', 'Group 1', 'Group 1 alkali metals (Li, Na, K, Rb, Cs, Fr) have 1 valence electron, are highly reactive, and readily form +1 ions.', 11, 'InorganicChemistry'),
('What is the oxidation state of oxygen in H₂O?', '-2', '+2', '0', '-1', '-2', 'In most compounds, oxygen has an oxidation state of -2. Exceptions: peroxides (-1), superoxides (-1/2), and OF₂ (+2).', 14, 'InorganicChemistry'),
('What is a coordination compound?', 'A compound with a central metal ion bonded to ligands', 'A compound containing only ionic bonds', 'A covalent compound with no metal', 'A compound formed under high pressure', 'A compound with a central metal ion bonded to ligands', 'Coordination compounds have a metal centre (often transition metal) surrounded by ligands (Lewis bases donating electron pairs). Example: [Fe(CN)₆]³⁻.', 25, 'InorganicChemistry'),
('What does Crystal Field Theory explain?', 'The splitting of d-orbital energies in metal complexes due to ligand interactions', 'The bonding in ionic crystals', 'The arrangement of atoms in a unit cell', 'The energy of atomic orbitals', 'The splitting of d-orbital energies in metal complexes due to ligand interactions', 'CFT: ligands create an electric field that splits d-orbitals into sets. The splitting energy (Δ) determines whether complexes are high-spin or low-spin.', 45, 'InorganicChemistry'),
('What is a chelate?', 'A ligand that binds to a metal through two or more donor atoms', 'A metal with multiple oxidation states', 'An inorganic polymer', 'A high-spin complex', 'A ligand that binds to a metal through two or more donor atoms', 'Chelating ligands (e.g. EDTA, en) form rings with the metal. The chelate effect makes them thermodynamically more stable than monodentate analogues.', 40, 'InorganicChemistry'),
('Which law describes the relationship between oxidation and reduction in electrochemistry?', 'Faraday''s law of electrolysis', 'Hess''s law', 'Le Chatelier''s principle', 'Raoult''s law', 'Faraday''s law of electrolysis', 'Faraday''s law: mass deposited = (M × I × t)/(n × F). F = 96485 C/mol. Relates charge passed to moles of substance oxidised/reduced.', 50, 'InorganicChemistry'),
('What is the trans effect in square planar complexes?', 'A trans ligand directs substitution to occur at the position opposite it', 'Two ligands on the same side have stronger bonds', 'Trans isomers are more stable', 'A ligand stabilises the opposite ligand', 'A trans ligand directs substitution to occur at the position opposite it', 'The trans effect: strong trans-directing ligands (CO, CN⁻, H⁻) labilise ligands opposite to them. Used in synthesis to control isomer formation (e.g. cisplatin synthesis).', 75, 'InorganicChemistry'),
('What characterises a superacid?', 'An acid stronger than 100% sulfuric acid (H₀ < -12)', 'An acid with pKa below zero', 'A polyprotic acid', 'An acid that fully dissociates in water', 'An acid stronger than 100% sulfuric acid (H₀ < -12)', 'Superacids (e.g. fluoroantimonic acid H₂F⁺SbF₆⁻) have Hammett acidity function H₀ < -12. They can protonate nearly any molecule, including weak bases.', 90, 'InorganicChemistry'),
('What is the Born-Haber cycle used for?', 'Calculating lattice energies of ionic compounds', 'Predicting reaction rates', 'Determining molecular geometry', 'Calculating bond dissociation energies', 'Calculating lattice energies of ionic compounds', 'The Born-Haber cycle applies Hess''s law to ionic compound formation, allowing calculation of lattice energy (which can''t be measured directly) from measurable quantities.', 60, 'InorganicChemistry'),
('In which hybridisation state is the central atom of a tetrahedral molecule?', 'sp³', 'sp²', 'sp', 'dsp²', 'sp³', 'sp³ hybridisation: one s and three p orbitals mix to give four equivalent hybrid orbitals pointing to tetrahedral corners (109.5°). Example: CH₄, NH₃.', 20, 'InorganicChemistry');

-- ============================================================
-- ORGANIC CHEMISTRY
-- ============================================================
INSERT INTO organicchemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What functional group is present in an aldehyde?', '-CHO (carbonyl at the end of a chain)', '-COOH', '-OH', '-NH₂', '-CHO (carbonyl at the end of a chain)', 'Aldehydes have a carbonyl group (C=O) at the terminal carbon (R-CHO). Ketones have the carbonyl in the middle (R-CO-R).', 12, 'OrganicChemistry'),
('What type of isomers have the same molecular formula but different connectivity?', 'Constitutional isomers', 'Enantiomers', 'Diastereomers', 'Conformational isomers', 'Constitutional isomers', 'Constitutional (structural) isomers differ in how atoms are connected. Stereoisomers have the same connectivity but different spatial arrangement.', 14, 'OrganicChemistry'),
('In an SN2 reaction, what happens to the stereochemistry at the carbon?', 'Inversion (Walden inversion)', 'Retention of configuration', 'Racemisation', 'No change', 'Inversion (Walden inversion)', 'SN2: the nucleophile attacks from the back of the leaving group. The configuration at the chiral centre inverts — like an umbrella flipping in the wind.', 28, 'OrganicChemistry'),
('Which reagent converts a primary alcohol to an aldehyde (not overoxidised to acid)?', 'PCC (pyridinium chlorochromate)', 'KMnO₄', 'K₂Cr₂O₇', 'LiAlH₄', 'PCC (pyridinium chlorochromate)', 'PCC in CH₂Cl₂ oxidises primary alcohols to aldehydes and stops there. KMnO₄ and K₂Cr₂O₇ continue to carboxylic acids.', 35, 'OrganicChemistry'),
('What is Markovnikov''s rule?', 'In addition to an alkene, H adds to the carbon with more H atoms already attached', 'Elimination occurs at the more substituted carbon', 'Reactions prefer the less stable carbocation', 'Addition occurs anti to the bulky group', 'In addition to an alkene, H adds to the carbon with more H atoms already attached', 'Markovnikov''s rule: H+ adds to the less substituted carbon, forming the more stable (more substituted) carbocation. Product: H on the C with more H''s.', 30, 'OrganicChemistry'),
('In electrophilic aromatic substitution, which group is ortho/para directing and activating?', '-OH (hydroxyl)', '-NO₂ (nitro)', '-COOH (carboxyl)', '-CF₃ (trifluoromethyl)', '-OH (hydroxyl)', 'Electron-donating groups (OH, NH₂, OR) activate the ring and direct to ortho/para positions. Electron-withdrawing groups (NO₂, COOH) deactivate and direct to meta.', 40, 'OrganicChemistry'),
('What is the product of ozonolysis of 2-butene (CH₃CH=CHCH₃) followed by reductive workup?', 'Two molecules of acetaldehyde (CH₃CHO)', 'Butanone and formaldehyde', 'Butanoic acid', 'Two molecules of acetic acid', 'Two molecules of acetaldehyde (CH₃CHO)', 'Ozonolysis cleaves double bonds. 2-Butene (CH₃CH=CHCH₃) gives two CH₃CHO (acetaldehyde) molecules with reductive workup (Zn/H₂O or DMS).', 50, 'OrganicChemistry'),
('What is a Diels-Alder reaction?', 'A [4+2] cycloaddition between a diene and a dienophile', 'An SN1 reaction of dienes', 'A 1,2-elimination', 'A nucleophilic addition to a ketone', 'A [4+2] cycloaddition between a diene and a dienophile', 'Diels-Alder is a concerted [4+2] pericyclic reaction. A conjugated diene (4π) reacts with a dienophile (2π) to form a cyclohexene. Stereospecific: syn addition.', 65, 'OrganicChemistry'),
('What determines the R/S designation of a chiral centre?', 'Priority of substituents by atomic number (CIP rules), then direction of decreasing priority', 'Whether the molecule rotates plane-polarised light right or left', 'The number of substituents', 'Whether the isomer is more stable', 'Priority of substituents by atomic number (CIP rules), then direction of decreasing priority', 'CIP rules: assign priority 1-4 by atomic number. With lowest priority pointing away, if 1→2→3 is clockwise = R; anticlockwise = S. Independent of optical rotation.', 55, 'OrganicChemistry'),
('What is retrosynthesis?', 'Working backwards from target molecule to simpler precursors', 'Synthesising a molecule in reverse conditions', 'Hydrolysing complex molecules', 'Analysing spectral data to identify structures', 'Working backwards from target molecule to simpler precursors', 'Retrosynthetic analysis (Corey): disconnect bonds in the target to reveal synthons, then find real reagents. The arrow (⇒) means "can be made from". Key skill in synthetic planning.', 80, 'OrganicChemistry');

-- ============================================================
-- ASTROPHYSICS
-- ============================================================
INSERT INTO astrophysics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is the closest star to Earth (other than the Sun)?', 'Proxima Centauri', 'Alpha Centauri A', 'Barnard''s Star', 'Sirius', 'Proxima Centauri', 'Proxima Centauri is ~4.24 light-years away. It is a red dwarf and part of the Alpha Centauri triple star system.', 11, 'Astrophysics'),
('What type of star is our Sun?', 'G-type main-sequence star (yellow dwarf)', 'Red giant', 'White dwarf', 'Neutron star', 'G-type main-sequence star (yellow dwarf)', 'The Sun is a G2V star: spectral type G, luminosity class V (main sequence). Surface temperature ~5778K. It will become a red giant in ~5 billion years.', 12, 'Astrophysics'),
('What does Hubble''s law state?', 'Galaxies recede from us at a speed proportional to their distance', 'All galaxies are moving toward a central point', 'The universe is static', 'Stars move in proportion to their mass', 'Galaxies recede from us at a speed proportional to their distance', 'v = H₀ × d, where H₀ ≈ 70 km/s/Mpc. This is evidence for the expanding universe and the Big Bang.', 22, 'Astrophysics'),
('What is a pulsar?', 'A rapidly rotating neutron star emitting beams of electromagnetic radiation', 'An exploding white dwarf', 'A type of variable star', 'A black hole emitting jets', 'A rapidly rotating neutron star emitting beams of electromagnetic radiation', 'Pulsars are neutron stars with strong magnetic fields. They emit beams from their magnetic poles; as they rotate, we detect regular pulses (like a lighthouse).', 35, 'Astrophysics'),
('What is the Chandrasekhar limit?', 'The maximum mass (~1.4 M☉) of a stable white dwarf', 'The minimum mass for a star to fuse hydrogen', 'The radius of a neutron star', 'The luminosity at which radiation pressure exceeds gravity', 'The maximum mass (~1.4 M☉) of a stable white dwarf', 'Above ~1.4 solar masses, electron degeneracy pressure cannot support a white dwarf against gravity. It will collapse to a neutron star or explode as a Type Ia supernova.', 55, 'Astrophysics'),
('What observational evidence supports the existence of dark matter?', 'Flat galaxy rotation curves inconsistent with visible mass', 'Galaxies rotating too slowly', 'The cosmic microwave background', 'Type Ia supernova brightness', 'Flat galaxy rotation curves inconsistent with visible mass', 'Stars at the outer edge of galaxies orbit as fast as inner stars. Newtonian gravity predicts slower speeds without extra unseen mass. Dark matter explains this flat rotation curve.', 65, 'Astrophysics'),
('What are gravitational waves?', 'Ripples in spacetime caused by accelerating massive objects', 'Electromagnetic radiation from pulsars', 'Sound waves in the interstellar medium', 'Waves caused by stellar magnetic fields', 'Ripples in spacetime caused by accelerating massive objects', 'Predicted by Einstein''s GR (1916), first directly detected by LIGO in 2015 from a binary black hole merger. They stretch and compress spacetime as they pass.', 70, 'Astrophysics'),
('What is the cosmic microwave background (CMB)?', 'Thermal radiation from 380,000 years after the Big Bang, now at ~2.7K', 'Radiation emitted by the Milky Way''s centre', 'Radiation from quasars', 'X-ray radiation from galaxy clusters', 'Thermal radiation from 380,000 years after the Big Bang, now at ~2.7K', 'The CMB was released when the universe cooled enough for protons and electrons to combine (recombination). Detected by Penzias & Wilson (1965), confirming the Big Bang.', 60, 'Astrophysics'),
('What is the Schwarzschild radius?', 'The radius within which an object becomes a black hole (event horizon)', 'The radius at which a star ignites fusion', 'The radius of the photon sphere', 'The orbital radius of the innermost stable orbit', 'The radius within which an object becomes a black hole (event horizon)', 'r_s = 2GM/c². For the Sun: ~3 km. If the Sun were compressed to this radius, it would form a black hole. Nothing inside r_s can escape.', 80, 'Astrophysics'),
('What powers a quasar?', 'Accretion of matter onto a supermassive black hole', 'Fusion of elements heavier than iron', 'Rapid stellar formation', 'Collision of two neutron stars', 'Accretion of matter onto a supermassive black hole', 'Quasars are the most luminous objects in the universe, powered by matter falling into supermassive black holes (10⁸-10¹⁰ M☉). The accretion disc emits enormous energy.', 75, 'Astrophysics');

-- ============================================================
-- ELECTROMAGNETICS
-- ============================================================
INSERT INTO electromagnetics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What is Ohm''s law?', 'V = IR (voltage = current × resistance)', 'P = IV', 'I = V²/R', 'V = I/R', 'V = IR (voltage = current × resistance)', 'Ohm''s law: V=IR. A voltage of 10V across a 5Ω resistor produces 2A of current. Applies to ohmic (linear) conductors.', 11, 'Electromagnetics'),
('What is Coulomb''s law?', 'The force between two charges is proportional to the product of charges and inversely proportional to r²', 'Force is proportional to the sum of charges', 'Force is proportional to distance', 'Charges attract regardless of sign', 'The force between two charges is proportional to the product of charges and inversely proportional to r²', 'F = kq₁q₂/r², where k = 8.99×10⁹ N·m²/C². Like charges repel, unlike attract. Analogous to Newton''s law of gravitation.', 13, 'Electromagnetics'),
('What does Faraday''s law of electromagnetic induction state?', 'EMF is induced equal to the rate of change of magnetic flux', 'A current-carrying conductor experiences a force in a magnetic field', 'Moving charges produce magnetic fields', 'Electric fields are created by stationary charges', 'EMF is induced equal to the rate of change of magnetic flux', 'ε = -dΦ/dt. A changing magnetic flux through a loop induces an EMF. The negative sign (Lenz''s law) means the induced current opposes the change.', 25, 'Electromagnetics'),
('What are Maxwell''s equations?', 'Four equations describing how electric and magnetic fields are generated and interact', 'Equations governing quantum electrodynamics', 'Laws of thermodynamics in electromagnetic form', 'Equations for electromagnetic wave speed in media', 'Four equations describing how electric and magnetic fields are generated and interact', 'Maxwell''s 4 equations: Gauss''s law (E), Gauss''s law (B), Faraday''s law, Ampere-Maxwell law. Together they predict electromagnetic waves travelling at c.', 38, 'Electromagnetics'),
('What is the skin effect?', 'At high frequencies, current flows mainly near the conductor surface', 'Conductors heat up at high voltages', 'Resistance decreases with increasing frequency', 'Magnetic fields penetrate deeper at high frequencies', 'At high frequencies, current flows mainly near the conductor surface', 'Skin depth δ = √(2ρ/ωμ). At high frequencies, current is confined to a thin surface layer. This increases effective resistance and is why HF cables use stranded wire.', 55, 'Electromagnetics'),
('What is a standing wave ratio (SWR) of 1 in a transmission line?', 'Perfect impedance matching — no reflections', 'Maximum reflection', 'Total mismatch', 'Half power reflection', 'Perfect impedance matching — no reflections', 'SWR = (1+|Γ|)/(1-|Γ|) where Γ is reflection coefficient. SWR=1 means Γ=0 (no reflection, all power delivered). SWR>1 means some power is reflected back.', 65, 'Electromagnetics'),
('What is the Biot-Savart law used to calculate?', 'Magnetic field produced by a current-carrying conductor', 'Electric field from a charge distribution', 'EMF induced by a changing flux', 'Force on a charge in a field', 'Magnetic field produced by a current-carrying conductor', 'dB = (μ₀/4π)(I dl × r̂)/r². Integrating over a conductor gives the total B field. Analogous to Coulomb''s law but for magnetic fields from currents.', 45, 'Electromagnetics'),
('What is a waveguide?', 'A structure that guides electromagnetic waves along a path with low loss', 'A device that amplifies radio waves', 'An antenna that radiates in all directions', 'A passive filter circuit', 'A structure that guides electromagnetic waves along a path with low loss', 'Waveguides are hollow metal tubes (rectangular or circular) that confine EM waves by total internal reflection. They have a cutoff frequency below which propagation is impossible.', 70, 'Electromagnetics'),
('What is the relationship between electric field E and electric potential V?', 'E = -∇V (E is the negative gradient of V)', 'V = -∇E', 'E = ∇²V', 'V = ∇ × E', 'E = -∇V (E is the negative gradient of V)', 'Electric field is the negative gradient of potential: E = -∇V. This means E points in the direction of decreasing potential, from high to low V.', 35, 'Electromagnetics'),
('What is antenna gain?', 'The ratio of an antenna''s radiation intensity in a direction to an isotropic radiator', 'The amplification provided by an amplifier connected to an antenna', 'The total radiated power', 'The bandwidth of the antenna', 'The ratio of an antenna''s radiation intensity in a direction to an isotropic radiator', 'Antenna gain G = 4πU(θ,φ)/P_total vs. isotropic. A high-gain antenna focuses radiation in a specific direction (directivity × efficiency). Measured in dBi.', 80, 'Electromagnetics');

-- ============================================================
-- QUANTUM MECHANICS
-- ============================================================
INSERT INTO quantummechanics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What does the Heisenberg uncertainty principle state?', 'Position and momentum cannot both be precisely known simultaneously', 'Energy and time are always conserved', 'A particle cannot have zero energy', 'Quantum states collapse upon measurement', 'Position and momentum cannot both be precisely known simultaneously', 'ΔxΔp ≥ ℏ/2. This is not a measurement limitation but a fundamental property of quantum systems. Precise position means completely uncertain momentum and vice versa.', 13, 'QuantumMechanics'),
('What is wave-particle duality?', 'Quantum objects exhibit both wave and particle properties depending on observation', 'Waves can carry particles', 'Particles create waves when moving', 'Light is purely a wave', 'Quantum objects exhibit both wave and particle properties depending on observation', 'Demonstrated by the double-slit experiment: electrons create interference patterns (wave) but are detected as discrete hits (particle). De Broglie: λ = h/p.', 15, 'QuantumMechanics'),
('What is the physical meaning of |ψ|² in quantum mechanics?', 'The probability density of finding a particle at a given location', 'The energy of the particle', 'The momentum of the particle', 'The wavelength of the particle', 'The probability density of finding a particle at a given location', 'The Born interpretation: |ψ(x)|² gives the probability density. The probability of finding a particle between x and x+dx is |ψ(x)|²dx. The wave function must be normalised.', 25, 'QuantumMechanics'),
('What are the quantum numbers describing an electron in an atom?', 'n (principal), l (angular momentum), mₗ (magnetic), mₛ (spin)', 'n, m, s, p', 'Energy, momentum, spin, charge', 'x, y, z, spin', 'n (principal), l (angular momentum), mₗ (magnetic), mₛ (spin)', 'n=1,2,3... (shell), l=0 to n-1 (subshell: s,p,d,f), mₗ=-l to +l (orbital orientation), mₛ=±½ (spin). No two electrons can share all four (Pauli exclusion).', 28, 'QuantumMechanics'),
('What does the Pauli exclusion principle state?', 'No two fermions can occupy the same quantum state simultaneously', 'Particles cannot exceed the speed of light', 'Energy is conserved in quantum systems', 'Observable quantities come in discrete values', 'No two fermions can occupy the same quantum state simultaneously', 'Electrons (fermions, spin-½) cannot share all four quantum numbers. This gives atoms their structure and explains the periodic table and matter''s solidity.', 32, 'QuantumMechanics'),
('What is quantum tunnelling?', 'A particle penetrating through a potential energy barrier classically forbidden', 'Particles jumping between energy levels', 'A particle''s spin flipping', 'Quantum particles moving faster than light', 'A particle penetrating through a potential energy barrier classically forbidden', 'Tunnelling probability ∝ e^(-2κd) where κ = √(2m(V-E))/ℏ. Explains alpha decay, STM, and tunnel diodes. The particle has no classical path through the barrier.', 50, 'QuantumMechanics'),
('What is quantum entanglement?', 'Two particles sharing a quantum state such that measuring one instantly determines the other', 'Two particles occupying the same position', 'A particle splitting into two', 'Particles attracting each other at a quantum level', 'Two particles sharing a quantum state such that measuring one instantly determines the other', 'Entangled particles have correlated states regardless of separation. Measuring one collapses the joint state. Einstein called it "spooky action at a distance." Confirmed by Bell test experiments.', 60, 'QuantumMechanics'),
('What does the time-independent Schrödinger equation describe?', 'Stationary states (energy eigenstates) of a quantum system', 'Time evolution of all quantum systems', 'Relativistic quantum mechanics', 'The collapse of the wave function', 'Stationary states (energy eigenstates) of a quantum system', 'Ĥψ = Eψ. Solving this gives the allowed energy levels and wave functions. For the hydrogen atom, it yields the orbital structure and energy levels Eₙ = -13.6/n² eV.', 55, 'QuantumMechanics'),
('What is the significance of Bell''s theorem?', 'No local hidden variable theory can reproduce all quantum mechanical predictions', 'Quantum mechanics is incomplete', 'Particles have definite properties before measurement', 'Quantum mechanics is equivalent to classical mechanics at large scales', 'No local hidden variable theory can reproduce all quantum mechanical predictions', 'Bell (1964) showed quantum correlations violate inequalities that any local hidden variable theory must satisfy. Experimental violations confirm: quantum mechanics is fundamentally non-local.', 95, 'QuantumMechanics'),
('In the harmonic oscillator, what is the ground state energy?', 'ℏω/2 (the zero-point energy)', '0', 'ℏω', '2ℏω', 'ℏω/2 (the zero-point energy)', 'The quantum harmonic oscillator has energy levels Eₙ = (n+½)ℏω. The ground state (n=0) has E₀ = ℏω/2 ≠ 0. This zero-point energy is a direct consequence of the uncertainty principle.', 70, 'QuantumMechanics');

-- ============================================================
-- THERMODYNAMICS
-- ============================================================
INSERT INTO thermodynamics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
('What does the zeroth law of thermodynamics state?', 'If A is in thermal equilibrium with B and B with C, then A is in equilibrium with C', 'Energy is conserved in all processes', 'Entropy of the universe always increases', 'Absolute zero is unattainable', 'If A is in thermal equilibrium with B and B with C, then A is in equilibrium with C', 'The zeroth law defines thermal equilibrium and temperature. It is the basis for thermometers — a thermometer in equilibrium with an object reads the object''s temperature.', 12, 'Thermodynamics'),
('What is the first law of thermodynamics?', 'The total energy of an isolated system is conserved (ΔU = Q - W)', 'Entropy always increases', 'Heat flows from cold to hot spontaneously', 'Absolute zero cannot be reached', 'The total energy of an isolated system is conserved (ΔU = Q - W)', 'ΔU = Q - W: the change in internal energy equals heat added to the system minus work done by the system. This is conservation of energy for thermodynamic systems.', 12, 'Thermodynamics'),
('What is entropy a measure of?', 'The number of microscopic states consistent with a macroscopic state (disorder)', 'The total energy of a system', 'The temperature of a system', 'The heat capacity of a substance', 'The number of microscopic states consistent with a macroscopic state (disorder)', 'S = k_B ln(Ω) where Ω is the number of microstates (Boltzmann). Systems evolve toward maximum entropy (most probable macrostate). ΔS_universe ≥ 0 for all real processes.', 28, 'Thermodynamics'),
('What is the efficiency of an ideal Carnot engine?', 'η = 1 - T_cold/T_hot', 'η = T_hot/T_cold', 'η = 1 - Q_cold/Q_hot', 'η = W/Q_cold', 'η = 1 - T_cold/T_hot', 'Carnot efficiency depends only on the temperatures of the hot and cold reservoirs. No engine operating between two temperatures can be more efficient than a Carnot engine.', 35, 'Thermodynamics'),
('What is the Gibbs free energy (G) used to predict?', 'Spontaneity of a process at constant T and P', 'The rate of a reaction', 'The activation energy', 'The enthalpy of a reaction', 'Spontaneity of a process at constant T and P', 'ΔG = ΔH - TΔS. If ΔG < 0: spontaneous. ΔG > 0: non-spontaneous. ΔG = 0: equilibrium. The most useful criterion for spontaneity in chemistry/biology.', 38, 'Thermodynamics'),
('What does the equipartition theorem state?', 'Each degree of freedom contributes ½k_BT to the average energy', 'All molecules have equal energy at equilibrium', 'Energy is distributed equally among all particles', 'Temperature determines only kinetic energy', 'Each degree of freedom contributes ½k_BT to the average energy', 'Equipartition: each quadratic degree of freedom (translational, rotational, vibrational) gets ½k_BT energy on average. For monatomic ideal gas: 3 DOF → U = 3/2 nRT.', 50, 'Thermodynamics'),
('What is a phase transition?', 'A change of state (e.g. liquid to gas) at a characteristic temperature and pressure', 'A change in chemical composition', 'A change in the number of molecules', 'A reversible temperature change', 'A change of state (e.g. liquid to gas) at a characteristic temperature and pressure', 'Phase transitions (melting, boiling, sublimation) occur when ΔG = 0 between phases. First-order transitions have latent heat; second-order (e.g. ferromagnetic) do not.', 45, 'Thermodynamics'),
('What is the Maxwell-Boltzmann distribution?', 'The distribution of molecular speeds in an ideal gas', 'The energy distribution of photons', 'The distribution of electrons in metals', 'The distribution of pressures in a gas', 'The distribution of molecular speeds in an ideal gas', 'The MB distribution gives the probability of a molecule having a given speed at temperature T. It has a characteristic peak (most probable speed) that shifts right with increasing T.', 55, 'Thermodynamics'),
('What does the Clausius-Clapeyron equation describe?', 'How vapour pressure changes with temperature along a phase boundary', 'The efficiency of heat engines', 'The relationship between pressure and volume', 'The rate of evaporation', 'How vapour pressure changes with temperature along a phase boundary', 'dP/dT = L/(TΔV). For liquid-vapour: ln(P₂/P₁) = -(ΔH_vap/R)(1/T₂ - 1/T₁). Used to find boiling points at different pressures.', 65, 'Thermodynamics'),
('In statistical mechanics, what is the partition function Z?', 'The sum over all states of e^(-E/k_BT), linking microscopic states to thermodynamic properties', 'The number of accessible microstates', 'The total energy divided by k_BT', 'The number of particles in a system', 'The sum over all states of e^(-E/k_BT), linking microscopic states to thermodynamic properties', 'Z = Σ e^(-βEᵢ) where β=1/k_BT. All thermodynamic quantities follow: F=-k_BT ln Z, U=-∂ln Z/∂β, S=k_B(ln Z + βU). Z is the bridge between QM and thermodynamics.', 90, 'Thermodynamics');
