INSERT INTO analyticalchemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score) VALUES
-- ── ACID-BASE / pH / pKa ─────────────────────────────────────────────────────
('What is the pH of a 0.01 M HCl solution?', '1', '2', '12', '7', '2', 'HCl is a strong acid that fully dissociates; [H+] = 0.01 M so pH = -log(0.01) = 2.', 720),
('What is the pH of a 0.001 M NaOH solution at 25 °C?', '3', '11', '7', '1', '11', 'pOH = -log(0.001) = 3, so pH = 14 - 3 = 11.', 740),
('The pKa of acetic acid is 4.76. What is the Ka?', '1.74 x 10^-5', '4.76 x 10^-4', '5.76 x 10^-5', '1.74 x 10^-4', '1.74 x 10^-5', 'Ka = 10^(-pKa) = 10^(-4.76) = 1.74 x 10^-5.', 950),
('A weak acid HA has Ka = 1.0 x 10^-5. What is the approximate pH of a 0.10 M solution?', '5.0', '3.0', '7.0', '1.0', '3.0', 'pH = 0.5*(pKa - log C) = 0.5*(5 + 1) = 3.0 for a weak acid using the approximation.', 1050),
('Which of the following is a conjugate acid-base pair?', 'HCl and NaCl', 'H2SO4 and SO4^2-', 'CH3COOH and CH3COO-', 'NH3 and N2H4', 'CH3COOH and CH3COO-', 'A conjugate pair differs by exactly one proton; acetic acid loses H+ to give acetate.', 820),
('At 25 °C, what is the Kw (ion product of water)?', '1.0 x 10^-14', '1.0 x 10^-7', '1.0 x 10^7', '1.0 x 10^-12', '1.0 x 10^-14', 'Kw = [H+][OH-] = 1.0 x 10^-14 at 25 °C by definition.', 700),
-- ── BUFFERS / HENDERSON-HASSELBALCH ──────────────────────────────────────────
('According to the Henderson-Hasselbalch equation, what is the pH when [A-]/[HA] = 10 and pKa = 4.76?', '5.76', '3.76', '4.76', '6.76', '5.76', 'pH = pKa + log([A-]/[HA]) = 4.76 + log(10) = 4.76 + 1 = 5.76.', 820),
('A buffer contains 0.10 M acetic acid (pKa = 4.76) and 0.20 M sodium acetate. What is the pH?', '5.06', '4.46', '4.76', '5.46', '5.06', 'pH = 4.76 + log(0.20/0.10) = 4.76 + 0.30 = 5.06.', 900),
('Buffer capacity is greatest when:', 'pH >> pKa', 'pH = pKa', 'pH << pKa', '[HA] >> [A-]', 'pH = pKa', 'When pH = pKa the ratio [A-]/[HA] = 1, giving maximum resistance to pH change.', 950),
('Which pair would make the best buffer at pH 7.4?', 'Acetic acid / acetate (pKa 4.76)', 'Phosphate H2PO4-/HPO4^2- (pKa 7.21)', 'Carbonate H2CO3/HCO3- (pKa 6.35)', 'Ammonia / ammonium (pKa 9.25)', 'Phosphate H2PO4-/HPO4^2- (pKa 7.21)', 'Effective buffering occurs within ±1 pH unit of the pKa; 7.21 is closest to 7.4.', 980),
-- ── TITRATIONS ───────────────────────────────────────────────────────────────
('In a strong acid-strong base titration, what is the pH at the equivalence point?', '7', '< 7', '> 7', 'Depends on concentration', '7', 'At the equivalence point only water and a neutral salt are present, giving pH = 7.', 720),
('Which indicator is most suitable for a strong acid-weak base titration?', 'Phenolphthalein (pH range 8.2-10.0)', 'Methyl orange (pH range 3.1-4.4)', 'Litmus (pH range 6.0-7.0)', 'Alizarin yellow (pH range 10-12)', 'Methyl orange (pH range 3.1-4.4)', 'The equivalence point of a strong acid-weak base falls below pH 7, within the range of methyl orange.', 1050),
('How many moles of NaOH are needed to reach the equivalence point when titrating 25.00 mL of 0.100 M H2SO4?', '0.005 mol', '0.0025 mol', '0.010 mol', '0.0050 mol', '0.005 mol', 'H2SO4 is diprotic; moles H2SO4 = 0.025 L x 0.100 mol/L = 0.0025 mol, needing 0.0050 mol NaOH.', 1100),
('In a weak acid-strong base titration, the half-equivalence point is characterised by:', 'pH = 7', 'pH = pKa of the acid', 'pH = 14 - pKa', '[HA] = 0', 'pH = pKa of the acid', 'At the half-equivalence point [HA] = [A-], so the Henderson-Hasselbalch equation gives pH = pKa.', 900),
('Potentiometric titration detects the equivalence point by:', 'A colour change in the solution', 'A sharp change in electrode potential', 'A temperature maximum', 'Precipitation of an insoluble salt', 'A sharp change in electrode potential', 'Potentiometric titration tracks cell potential vs. volume added; a steep inflection marks the equivalence point.', 1000),
-- ── GRAVIMETRIC ANALYSIS ─────────────────────────────────────────────────────
('In gravimetric analysis, Ba2+ is precipitated as BaSO4 (MM = 233.4 g/mol). If 0.500 g BaSO4 is obtained from a sample, how many mmol of Ba2+ were present?', '2.14 mmol', '1.07 mmol', '4.28 mmol', '0.214 mmol', '2.14 mmol', 'moles BaSO4 = 0.500 g / 233.4 g/mol = 0.00214 mol = 2.14 mmol; 1:1 stoichiometry with Ba2+.', 1100),
('Which property is most important for a gravimetric precipitate?', 'High solubility in water', 'Low molar mass', 'Low solubility and known stoichiometry', 'Coloured appearance', 'Low solubility and known stoichiometry', 'A gravimetric precipitate must have negligible solubility (to ensure complete precipitation) and a definite composition.', 850),
('Digestion of a gravimetric precipitate is performed to:', 'Dissolve excess reagent', 'Increase particle size and purity', 'Reduce the molar mass of the precipitate', 'Increase the solubility product', 'Increase particle size and purity', 'Digestion (heating the precipitate in the mother liquor) causes small crystals to dissolve and reprecipitate as larger, purer crystals.', 1150),
-- ── BEER-LAMBERT LAW / UV-VIS ────────────────────────────────────────────────
('The Beer-Lambert law states that absorbance A equals:', 'epsilon * b / c', 'epsilon * b * c', 'log(I/I0)', 'c / (epsilon * b)', 'epsilon * b * c', 'A = epsilon * b * c, where epsilon is molar absorptivity, b is path length, and c is concentration.', 780),
('A solution has an absorbance of 0.600 at 550 nm. What is its transmittance?', '25.1%', '40.0%', '60.0%', '6.0%', '25.1%', 'T = 10^(-A) = 10^(-0.600) = 0.251, i.e. 25.1% transmittance.', 980),
('The molar absorptivity (epsilon) has units of:', 'L mol^-1 cm^-1', 'mol L^-1 cm', 'cm^-1', 'dimensionless', 'L mol^-1 cm^-1', 'Rearranging A = epsilon*b*c: epsilon = A/(b*c), so units are (dimensionless)/(cm * mol/L) = L mol^-1 cm^-1.', 900),
('Beer-Lambert linearity breaks down at high analyte concentrations because:', 'The detector becomes more sensitive', 'Solute-solute interactions change the effective molar absorptivity', 'Path length increases', 'The light source becomes brighter', 'Solute-solute interactions change the effective molar absorptivity', 'At high concentration, intermolecular interactions alter the absorptivity, causing a negative deviation from linearity.', 1200),
('In UV-Vis spectrophotometry, an isosbestic point indicates:', 'Maximum absorbance of a single species', 'A wavelength where two species have equal absorbance', 'The detection limit of the instrument', 'The molar absorptivity is zero', 'A wavelength where two species have equal absorbance', 'An isosbestic point is a wavelength at which the total absorbance is invariant as one species converts to another.', 1350),
-- ── CHROMATOGRAPHY ───────────────────────────────────────────────────────────
('In HPLC, the retention factor k is defined as:', '(tR - tM) / tM', 'tR / tM', '(tM - tR) / tR', 'tR * tM', '(tR - tM) / tM', 'k = (tR - tM)/tM where tR is the retention time of the analyte and tM is the dead (void) time.', 1000),
('In reversed-phase HPLC, the stationary phase is:', 'Polar silica', 'Non-polar (e.g. C18-bonded silica)', 'Ion-exchange resin', 'Alumina', 'Non-polar (e.g. C18-bonded silica)', 'Reversed-phase HPLC uses a non-polar stationary phase and a polar mobile phase, opposite to normal-phase.', 820),
('In gas chromatography (GC), analytes are separated primarily based on:', 'Their molecular masses', 'Their volatility and interaction with the stationary phase', 'Their UV absorbance', 'Their ionic charge', 'Their volatility and interaction with the stationary phase', 'GC separates compounds by differences in boiling point (volatility) and affinity for the stationary phase at a given temperature.', 850),
('In thin-layer chromatography (TLC), the Rf value is defined as:', 'Distance travelled by solute / distance travelled by solvent front', 'Distance travelled by solvent / distance travelled by solute', 'Retention time / void time', 'Plate height / column length', 'Distance travelled by solute / distance travelled by solvent front', 'Rf = distance_solute / distance_solvent_front; it ranges from 0 to 1.', 750),
('The van Deemter equation describes the relationship between:', 'Absorbance and concentration', 'Plate height (H) and mobile phase velocity (u)', 'Retention factor and temperature', 'Signal-to-noise ratio and scan time', 'Plate height (H) and mobile phase velocity (u)', 'H = A + B/u + Cu; the equation identifies eddy diffusion (A), longitudinal diffusion (B/u), and mass transfer (Cu) contributions to band broadening.', 1450),
('In gas chromatography, a flame ionisation detector (FID) is most sensitive to:', 'Inorganic gases', 'Organic compounds containing C-H bonds', 'Halogenated compounds', 'Water vapour', 'Organic compounds containing C-H bonds', 'FID burns organic analytes in a H2/air flame; the ions produced give a current proportional to carbon content.', 900),
('The selectivity factor (alpha) between two analytes in chromatography is:', 'k2 / k1 (k2 > k1)', 'k1 * k2', '(k2 - k1) / k1', 'k1 / k2', 'k2 / k1 (k2 > k1)', 'alpha = k2/k1 where k2 > k1; alpha = 1 means no selectivity between the two compounds.', 1050),
-- ── MASS SPECTROMETRY ────────────────────────────────────────────────────────
('In mass spectrometry, the x-axis is m/z. What do m and z represent?', 'Mass number and zero', 'Molecular mass and charge number', 'Molar mass and atomic number', 'Mass and valence', 'Molecular mass and charge number', 'm/z is the mass-to-charge ratio; m is the ionic mass (in Da) and z is the number of elementary charges.', 800),
('Which ionisation technique is considered a "soft" ionisation method that preserves intact molecular ions of large biomolecules?', 'Electron ionisation (EI)', 'Chemical ionisation (CI)', 'Matrix-assisted laser desorption/ionisation (MALDI)', 'Fast atom bombardment (FAB)', 'Matrix-assisted laser desorption/ionisation (MALDI)', 'MALDI uses a matrix to absorb laser energy and gently desorb/ionise large molecules with minimal fragmentation.', 1050),
('A compound has a molecular ion at m/z = 78. Loss of CO (28 Da) gives a fragment at m/z = 50. What is the mass of the remaining fragment?', '50', '28', '78', '106', '50', 'Fragment ion m/z = 78 - 28 = 50 Da after loss of one CO molecule.', 820),
('In EI mass spectrometry, the base peak is defined as:', 'The molecular ion peak', 'The most abundant fragment peak (set to 100%)', 'The peak at lowest m/z', 'The peak corresponding to M+1', 'The most abundant fragment peak (set to 100%)', 'The base peak is the tallest peak in the mass spectrum, assigned a relative intensity of 100%.', 780),
-- ── NMR BASICS ───────────────────────────────────────────────────────────────
('In 1H NMR spectroscopy, chemical shift (delta) is measured in:', 'Hz', 'ppm relative to TMS', 'cm^-1', 'eV', 'ppm relative to TMS', 'Chemical shift is reported in parts per million (ppm) relative to tetramethylsilane (TMS) set at 0.00 ppm.', 800),
('A proton adjacent to an electron-withdrawing group appears at a chemical shift that is:', 'Shifted upfield (lower ppm)', 'Shifted downfield (higher ppm)', 'Unchanged', 'Negative ppm', 'Shifted downfield (higher ppm)', 'Electron-withdrawing groups deshield nearby protons, reducing electron density and causing a downfield shift to higher ppm.', 900),
('In 1H NMR, a doublet arises because the observed proton has:', 'No adjacent protons', 'One adjacent non-equivalent proton', 'Two adjacent non-equivalent protons', 'Three adjacent non-equivalent protons', 'One adjacent non-equivalent proton', 'The n+1 rule: n = 1 adjacent proton gives n+1 = 2 lines, i.e. a doublet.', 850),
-- ── ATOMIC ABSORPTION / EMISSION ─────────────────────────────────────────────
('Atomic absorption spectroscopy (AAS) measures:', 'Emission of photons by excited atoms', 'Absorption of specific wavelengths by ground-state atoms', 'Fluorescence from atomic species', 'Scattering of X-rays by electrons', 'Absorption of specific wavelengths by ground-state atoms', 'AAS quantifies elements by measuring the reduction in light intensity at a characteristic wavelength as it passes through an atomic vapour.', 830),
('In flame atomic emission spectrometry, the yellow colour of a sodium flame corresponds to the spectral line at approximately:', '589 nm', '430 nm', '766 nm', '253.7 nm', '589 nm', 'The sodium D-lines at ~589 nm arise from the 3p -> 3s electronic transition and produce the characteristic yellow flame colour.', 780),
('Ionisation interference in AAS can be reduced by adding:', 'A chelating agent such as EDTA', 'An ionisation buffer (excess of an easily ionised metal)', 'More fuel to the flame', 'A releasing agent such as lanthanum', 'An ionisation buffer (excess of an easily ionised metal)', 'Adding a large excess of an easily ionised element (e.g. Cs or K) suppresses ionisation of the analyte by driving the ionisation equilibrium toward neutral atoms.', 1300),
-- ── ELECTROCHEMISTRY / NERNST / POTENTIOMETRY ────────────────────────────────
('The Nernst equation at 25 °C for a half-reaction with n electrons is:', 'E = E° - (0.0592/n) log Q', 'E = E° + (0.0592/n) log Q', 'E = E° - (n/0.0592) log Q', 'E = RT/nF', 'E = E° - (0.0592/n) log Q', 'The Nernst equation is E = E° - (RT/nF)lnQ; at 25 °C, RT/F = 0.02569 V and converting ln to log10 gives the factor 0.0592/n.', 1150),
('A pH glass electrode is an example of which type of electrode?', 'Redox indicator electrode', 'Ion-selective electrode', 'Reference electrode', 'Coulometric electrode', 'Ion-selective electrode', 'The glass pH electrode is the most common ion-selective electrode; its membrane responds selectively to H+ activity.', 850),
('In potentiometric titration with a Ag/AgCl reference electrode system, what species is being measured?', 'Electrode current', 'Cell potential (voltage)', 'Solution resistance', 'Charge passed', 'Cell potential (voltage)', 'Potentiometry measures the equilibrium cell potential (EMF) at zero current as an indicator of analyte activity.', 800),
('Which electroanalytical technique is based on measuring the current at a fixed potential?', 'Potentiometry', 'Amperometry', 'Coulometry', 'Conductometry', 'Amperometry', 'Amperometry applies a constant potential and measures the resulting current, which is proportional to analyte concentration.', 1000),
-- ── SOLUBILITY PRODUCT (Ksp) ─────────────────────────────────────────────────
('The Ksp of AgCl is 1.8 x 10^-10. What is the molar solubility of AgCl in pure water?', '1.3 x 10^-5 M', '1.8 x 10^-10 M', '3.6 x 10^-10 M', '9.0 x 10^-6 M', '1.3 x 10^-5 M', 'If s is solubility, Ksp = s^2, so s = sqrt(1.8 x 10^-10) = 1.34 x 10^-5 M.', 1000),
('Adding excess Cl- to an AgCl solution will cause:', 'More AgCl to dissolve', 'AgCl precipitation (common ion effect)', 'No change in solubility', 'An increase in Ksp', 'AgCl precipitation (common ion effect)', 'The common ion effect: adding Cl- shifts the equilibrium AgCl(s) <=> Ag+ + Cl- to the left, decreasing solubility.', 900),
-- ── SIGNIFICANT FIGURES / ERROR / PRECISION / ACCURACY ───────────────────────
('How many significant figures are in the number 0.004050?', '6', '4', '3', '7', '4', 'Leading zeros are not significant; 0.004050 has 4 significant figures: 4, 0, 5, 0.', 720),
('Systematic error affects:', 'Precision but not accuracy', 'Accuracy but not precision', 'Neither precision nor accuracy', 'Both precision and accuracy equally', 'Accuracy but not precision', 'Systematic (determinate) errors shift all measurements in the same direction, affecting accuracy while precision (reproducibility) may remain high.', 870),
('A set of measurements is 10.1, 10.2, 10.1, 10.2, 10.1 g (true value = 12.0 g). This data set is best described as:', 'Accurate and precise', 'Accurate but not precise', 'Precise but not accurate', 'Neither precise nor accurate', 'Precise but not accurate', 'The values are tightly clustered (precise) but far from the true value of 12.0 g (not accurate).', 780),
-- ── CALIBRATION CURVES / LOD / LOQ ───────────────────────────────────────────
('The limit of detection (LOD) is conventionally defined as the signal that is equal to the blank signal plus:', '3 standard deviations of the blank', '2 standard deviations of the blank', '10 standard deviations of the blank', '1 standard deviation of the blank', '3 standard deviations of the blank', 'IUPAC defines LOD as the signal = blank + 3*sigma_blank, corresponding to a 99.87% confidence that the signal is not from noise.', 1200),
('The limit of quantification (LOQ) is typically defined as blank plus how many standard deviations of the blank?', '10', '3', '2', '5', '10', 'LOQ is conventionally set at blank + 10*sigma_blank, ensuring sufficient precision for quantitative measurement.', 1100),
('In a linear calibration curve y = mx + b, the sensitivity of the method is represented by:', 'The intercept b', 'The slope m', 'The R^2 value', 'The range of concentrations used', 'The slope m', 'Sensitivity is the change in signal per unit change in concentration, which equals the slope m of the calibration line.', 950),
('An external standard calibration curve is constructed by:', 'Measuring the sample without any standards', 'Preparing known-concentration standards and plotting signal vs. concentration', 'Adding a known amount of analyte to each sample', 'Using an internal standard in only the sample solution', 'Preparing known-concentration standards and plotting signal vs. concentration', 'External calibration uses a series of independently prepared standards to construct the signal vs. concentration relationship.', 820);
