INSERT INTO anatomy (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
-- SKELETAL SYSTEM (Bones & Joints) --
('Which bone is the longest in the human body?', 'Femur', 'Tibia', 'Humerus', 'Fibula', 'Femur', 'The femur (thigh bone) is the longest and strongest bone in the human body.', 720, 'Anatomy'),
('How many bones are in the adult human body?', '206', '208', '212', '196', '206', 'The adult human skeleton consists of 206 bones, reduced from approximately 270 in infancy through fusion.', 750, 'Anatomy'),
('Which carpal bone is most commonly fractured?', 'Scaphoid', 'Lunate', 'Trapezium', 'Hamate', 'Scaphoid', 'The scaphoid is the most frequently fractured carpal bone, typically from a fall on an outstretched hand.', 980, 'Anatomy'),
('What type of joint is the hip joint?', 'Ball-and-socket joint', 'Hinge joint', 'Saddle joint', 'Pivot joint', 'Ball-and-socket joint', 'The hip joint is a ball-and-socket synovial joint, allowing multiaxial movement between the femoral head and the acetabulum.', 730, 'Anatomy'),
('Which bone forms the posterior part of the hard palate?', 'Palatine bone', 'Maxilla', 'Vomer', 'Sphenoid bone', 'Palatine bone', 'The horizontal plates of the paired palatine bones form the posterior one-third of the hard palate.', 1050, 'Anatomy'),
('The olecranon process is located on which bone?', 'Ulna', 'Radius', 'Humerus', 'Scapula', 'Ulna', 'The olecranon is the bony projection at the proximal end of the ulna that forms the point of the elbow.', 960, 'Anatomy'),
('Which suture joins the frontal and parietal bones?', 'Coronal suture', 'Sagittal suture', 'Lambdoid suture', 'Squamous suture', 'Coronal suture', 'The coronal suture is a fibrous joint that runs transversely across the skull separating the frontal bone from the two parietal bones.', 1100, 'Anatomy'),
-- MUSCULAR SYSTEM --
('Which muscle is responsible for plantarflexion and is nicknamed the "toe dancer''s muscle"?', 'Gastrocnemius', 'Tibialis anterior', 'Peroneus longus', 'Soleus', 'Gastrocnemius', 'The gastrocnemius is the large, superficial calf muscle primarily responsible for plantarflexion when the knee is extended.', 800, 'Anatomy'),
('The rotator cuff is composed of four muscles; which of the following is NOT one of them?', 'Teres major', 'Supraspinatus', 'Infraspinatus', 'Subscapularis', 'Teres major', 'The rotator cuff consists of supraspinatus, infraspinatus, teres minor, and subscapularis; teres major is a separate muscle.', 1200, 'Anatomy'),
('Which muscle is the primary flexor of the forearm at the elbow?', 'Brachialis', 'Biceps brachii', 'Brachioradialis', 'Coracobrachialis', 'Brachialis', 'The brachialis lies deep to the biceps brachii and is the most powerful flexor of the elbow regardless of forearm position.', 1300, 'Anatomy'),
('What is the origin of the deltoid muscle?', 'Clavicle, acromion, and spine of scapula', 'Clavicle and coracoid process', 'Acromion and coracoid process', 'Greater tubercle of humerus', 'Clavicle, acromion, and spine of scapula', 'The deltoid originates from the lateral third of the clavicle, the acromion, and the spine of the scapula.', 1150, 'Anatomy'),
('Which muscle forms the bulk of the anterior abdominal wall and is referred to as the "six-pack" muscle?', 'Rectus abdominis', 'External oblique', 'Internal oblique', 'Transversus abdominis', 'Rectus abdominis', 'The rectus abdominis is the paired, segmented vertical muscle of the anterior abdomen responsible for trunk flexion.', 710, 'Anatomy'),
-- HEART & CIRCULATORY ANATOMY --
('Which valve separates the left atrium from the left ventricle?', 'Mitral valve', 'Tricuspid valve', 'Aortic valve', 'Pulmonary valve', 'Mitral valve', 'The mitral (bicuspid) valve has two leaflets and controls blood flow from the left atrium into the left ventricle.', 760, 'Anatomy'),
('The sinoatrial node, the heart''s primary pacemaker, is located in which chamber?', 'Right atrium', 'Left atrium', 'Right ventricle', 'Left ventricle', 'Right atrium', 'The sinoatrial node is situated in the wall of the right atrium near the opening of the superior vena cava.', 870, 'Anatomy'),
('Which artery supplies the anterior wall of the left ventricle and the interventricular septum?', 'Left anterior descending artery', 'Right coronary artery', 'Left circumflex artery', 'Posterior descending artery', 'Left anterior descending artery', 'The left anterior descending (LAD) artery is a branch of the left coronary artery and is commonly called "the widow maker."', 1020, 'Anatomy'),
('The fossa ovalis is a remnant of which fetal structure?', 'Foramen ovale', 'Ductus arteriosus', 'Ductus venosus', 'Umbilical vein', 'Foramen ovale', 'The fossa ovalis is an oval depression in the interatrial septum representing the closed foramen ovale of fetal circulation.', 1180, 'Anatomy'),
('Which great vessel carries deoxygenated blood from the right ventricle to the lungs?', 'Pulmonary artery', 'Pulmonary vein', 'Aorta', 'Superior vena cava', 'Pulmonary artery', 'The pulmonary artery (pulmonary trunk) is unique in being an artery that carries deoxygenated blood to the lungs for gas exchange.', 720, 'Anatomy'),
-- RESPIRATORY ANATOMY --
('The carina is a ridge of cartilage located at the bifurcation of the trachea into which structures?', 'Left and right main bronchi', 'Left and right secondary bronchi', 'Bronchioles and alveoli', 'Larynx and trachea', 'Left and right main bronchi', 'The carina is the internal keel-like ridge at the level of the sternal angle where the trachea divides into the left and right main (primary) bronchi.', 1250, 'Anatomy'),
('Which lobe of the right lung is separated from the middle lobe by the horizontal fissure?', 'Upper lobe', 'Lower lobe', 'Lingula', 'Cardiac notch', 'Upper lobe', 'The horizontal fissure of the right lung separates the upper lobe from the middle lobe, running at the level of the 4th costal cartilage.', 1050, 'Anatomy'),
('The epiglottis is composed of which type of cartilage?', 'Elastic cartilage', 'Hyaline cartilage', 'Fibrocartilage', 'Calcified cartilage', 'Elastic cartilage', 'The epiglottis is made of elastic cartilage, which allows it to fold down over the glottis during swallowing to prevent aspiration.', 1350, 'Anatomy'),
('What is the functional unit of gas exchange in the lung?', 'Alveolus', 'Bronchiole', 'Respiratory bronchiole', 'Alveolar duct', 'Alveolus', 'The alveolus is the tiny air sac in the lung where oxygen and carbon dioxide are exchanged between air and blood across a thin membrane.', 700, 'Anatomy'),
-- DIGESTIVE ANATOMY --
('The hepatopancreatic ampulla (ampulla of Vater) opens into which part of the small intestine?', 'Second part of duodenum', 'First part of duodenum', 'Jejunum', 'Ileum', 'Second part of duodenum', 'The ampulla of Vater, where the common bile duct and main pancreatic duct unite, opens into the descending (second) part of the duodenum.', 1280, 'Anatomy'),
('Which part of the large intestine lacks taeniae coli, haustra, and omental appendices?', 'Rectum', 'Sigmoid colon', 'Ascending colon', 'Transverse colon', 'Rectum', 'The rectum lacks the three anatomical features (taeniae coli, haustra, and omental appendices) that characterize the rest of the large intestine.', 1380, 'Anatomy'),
('The liver receives its dual blood supply from the hepatic artery and which other vessel?', 'Portal vein', 'Hepatic vein', 'Inferior vena cava', 'Splenic vein', 'Portal vein', 'The hepatic portal vein delivers nutrient-rich blood from the GI tract to the liver, contributing about 75% of its total blood supply.', 900, 'Anatomy'),
('Which sphincter controls passage of chyme from the stomach into the duodenum?', 'Pyloric sphincter', 'Ileocecal valve', 'Cardiac sphincter', 'Internal anal sphincter', 'Pyloric sphincter', 'The pyloric sphincter is a thickening of the circular smooth muscle at the gastroduodenal junction that regulates gastric emptying.', 760, 'Anatomy'),
-- NERVOUS SYSTEM --
('Which cranial nerve is responsible for the "gag reflex" afferent limb?', 'Glossopharyngeal nerve (CN IX)', 'Vagus nerve (CN X)', 'Facial nerve (CN VII)', 'Trigeminal nerve (CN V)', 'Glossopharyngeal nerve (CN IX)', 'The afferent limb of the gag reflex is carried by the glossopharyngeal nerve (CN IX) from the posterior pharynx.', 1400, 'Anatomy'),
('The Broca''s area, responsible for speech production, is located in which lobe of the brain?', 'Frontal lobe', 'Temporal lobe', 'Parietal lobe', 'Occipital lobe', 'Frontal lobe', 'Broca''s area is located in the inferior frontal gyrus of the dominant frontal lobe and controls the motor production of speech.', 950, 'Anatomy'),
('Which tract carries pain and temperature sensation from the body to the brain?', 'Lateral spinothalamic tract', 'Dorsal columns', 'Corticospinal tract', 'Rubrospinal tract', 'Lateral spinothalamic tract', 'The lateral spinothalamic tract (anterolateral system) carries pain and temperature from the contralateral side of the body to the thalamus.', 1100, 'Anatomy'),
('The cauda equina is formed by nerve roots below which vertebral level?', 'L1', 'L3', 'T12', 'S1', 'L1', 'The spinal cord typically ends at L1-L2 in adults; below this level the nerve roots form the cauda equina (horse''s tail).', 1200, 'Anatomy'),
('Which structure connects the two cerebral hemispheres and is the largest white matter commissure?', 'Corpus callosum', 'Anterior commissure', 'Posterior commissure', 'Fornix', 'Corpus callosum', 'The corpus callosum is the largest commissure in the brain, containing approximately 200 million axons connecting the two cerebral hemispheres.', 800, 'Anatomy'),
('The circle of Willis is formed by anastomoses of which arteries? Which vessel is NOT part of it?', 'Vertebral artery', 'Anterior cerebral artery', 'Posterior communicating artery', 'Middle cerebral artery', 'Vertebral artery', 'The vertebral arteries join to form the basilar artery, which then contributes to the circle of Willis, but the vertebral arteries themselves are not part of the circle.', 1600, 'Anatomy'),
-- EYE & EAR --
('Which layer of the eye contains the photoreceptors (rods and cones)?', 'Retina', 'Choroid', 'Sclera', 'Ciliary body', 'Retina', 'The retina is the innermost layer of the eye and contains the photoreceptor cells — rods for dim light and cones for color vision.', 740, 'Anatomy'),
('The malleus, incus, and stapes are collectively known as what?', 'Ossicles', 'Cochlear bones', 'Tympanic bones', 'Labyrinthine bones', 'Ossicles', 'The three ossicles (auditory bones) of the middle ear transmit vibrations from the tympanic membrane to the oval window of the inner ear.', 770, 'Anatomy'),
('The aqueous humor is produced by which structure in the eye?', 'Ciliary body', 'Choroid plexus', 'Retinal pigment epithelium', 'Iris', 'Ciliary body', 'Aqueous humor is secreted by the non-pigmented epithelium of the ciliary body and drains through the trabecular meshwork.', 1150, 'Anatomy'),
('Which cranial nerve innervates the lateral rectus muscle of the eye?', 'Abducens nerve (CN VI)', 'Oculomotor nerve (CN III)', 'Trochlear nerve (CN IV)', 'Optic nerve (CN II)', 'Abducens nerve (CN VI)', 'The abducens nerve (CN VI) solely innervates the lateral rectus muscle, which abducts the eye.', 1020, 'Anatomy'),
-- ENDOCRINE GLANDS --
('The islets of Langerhans are found in which organ?', 'Pancreas', 'Liver', 'Spleen', 'Adrenal gland', 'Pancreas', 'The islets of Langerhans are clusters of endocrine cells scattered throughout the pancreas that produce insulin, glucagon, and somatostatin.', 800, 'Anatomy'),
('Which zone of the adrenal cortex produces aldosterone?', 'Zona glomerulosa', 'Zona fasciculata', 'Zona reticularis', 'Adrenal medulla', 'Zona glomerulosa', 'The outermost zona glomerulosa is the exclusive site of aldosterone synthesis, which regulates sodium and potassium balance.', 1380, 'Anatomy'),
('The posterior pituitary (neurohypophysis) stores and releases which hormones?', 'ADH and oxytocin', 'GH and prolactin', 'TSH and ACTH', 'FSH and LH', 'ADH and oxytocin', 'ADH (vasopressin) and oxytocin are synthesized in the hypothalamus and transported to the posterior pituitary for storage and release.', 1050, 'Anatomy'),
('Which gland, located in the mediastinum, is responsible for T-cell maturation?', 'Thymus', 'Thyroid', 'Parathyroid', 'Pineal gland', 'Thymus', 'The thymus is a bilobed gland in the anterior superior mediastinum where immature T-lymphocytes mature and become immunocompetent.', 900, 'Anatomy'),
-- URINARY / RENAL ANATOMY --
('The functional unit of the kidney is called what?', 'Nephron', 'Glomerulus', 'Loop of Henle', 'Collecting duct', 'Nephron', 'The nephron is the structural and functional unit of the kidney, consisting of the glomerulus and renal tubules.', 720, 'Anatomy'),
('The detrusor muscle is found in the wall of which organ?', 'Urinary bladder', 'Ureter', 'Renal pelvis', 'Urethra', 'Urinary bladder', 'The detrusor muscle is the thick smooth muscle layer of the urinary bladder wall that contracts during micturition to expel urine.', 870, 'Anatomy'),
-- REPRODUCTIVE ANATOMY --
('In males, which structure connects the epididymis to the ejaculatory duct?', 'Ductus deferens (vas deferens)', 'Seminal vesicle duct', 'Efferent ductules', 'Prostatic urethra', 'Ductus deferens (vas deferens)', 'The ductus deferens (vas deferens) is a muscular tube that carries sperm from the epididymis to the ejaculatory duct within the prostate.', 1100, 'Anatomy'),
('The uterine tube (fallopian tube) is divided into four parts; which part is widest and longest?', 'Ampulla', 'Isthmus', 'Infundibulum', 'Intramural part', 'Ampulla', 'The ampulla is the longest and widest portion of the uterine tube and is the most common site of fertilization.', 1250, 'Anatomy'),
-- LYMPHATIC SYSTEM --
('The thoracic duct drains lymph from all regions EXCEPT which?', 'Right upper limb and right side of the thorax, head, and neck', 'Lower limbs', 'Left side of the thorax', 'Abdominal viscera', 'Right upper limb and right side of the thorax, head, and neck', 'The right lymphatic duct drains the right upper limb and right head/neck/thorax; the thoracic duct drains everything else.', 1550, 'Anatomy'),
('Lymph from the lower extremities first passes through which lymph node group?', 'Inguinal lymph nodes', 'Popliteal lymph nodes', 'Iliac lymph nodes', 'Para-aortic lymph nodes', 'Inguinal lymph nodes', 'The superficial inguinal lymph nodes are the primary regional nodes receiving lymph from the lower extremities, perineum, and external genitalia.', 950, 'Anatomy'),
-- ANATOMICAL TERMINOLOGY --
('Which anatomical plane divides the body into anterior (front) and posterior (back) halves?', 'Coronal (frontal) plane', 'Sagittal plane', 'Transverse (axial) plane', 'Oblique plane', 'Coronal (frontal) plane', 'The coronal (frontal) plane is a vertical plane that divides the body into anterior and posterior sections.', 700, 'Anatomy'),
('In anatomical terminology, "medial" means closer to what reference point?', 'The midline of the body', 'The surface of the body', 'The head', 'The point of attachment of a limb', 'The midline of the body', 'Medial refers to structures closer to the midline (midsagittal plane) of the body, whereas lateral refers to structures farther from the midline.', 700, 'Anatomy'),
-- HISTOLOGY BASICS --
('Which type of epithelium lines the trachea and is characterized by cells that appear to be in multiple layers but all contact the basement membrane?', 'Pseudostratified columnar epithelium', 'Stratified squamous epithelium', 'Simple columnar epithelium', 'Transitional epithelium', 'Pseudostratified columnar epithelium', 'Pseudostratified ciliated columnar epithelium lines most of the respiratory tract; all cells touch the basement membrane despite their nuclei being at different levels.', 1400, 'Anatomy'),
('Which connective tissue cell type is responsible for producing collagen fibers?', 'Fibroblast', 'Macrophage', 'Mast cell', 'Plasma cell', 'Fibroblast', 'Fibroblasts are the principal cells of connective tissue proper and are responsible for synthesizing collagen, elastin, and ground substance.', 980, 'Anatomy'),
('Transitional epithelium (urothelium) is characteristically found lining which structures?', 'Urinary bladder, ureters, and renal pelvis', 'Small intestine and colon', 'Trachea and bronchi', 'Esophagus and vagina', 'Urinary bladder, ureters, and renal pelvis', 'Transitional epithelium is specialized to stretch and recoil, making it ideal for lining the urinary bladder, ureters, and renal pelvis.', 1100, 'Anatomy');
