INSERT INTO biochemistry (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
-- AMINO ACIDS & PROTEIN STRUCTURE --
('What type of bond links amino acids in a polypeptide chain?', 'Peptide bond', 'Hydrogen bond', 'Disulfide bond', 'Glycosidic bond', 'Peptide bond', 'Amino acids are joined by peptide (amide) bonds formed between the carboxyl group of one amino acid and the amino group of the next.', 730, 'Biochemistry'),
('Which level of protein structure refers to the sequence of amino acids?', 'Primary structure', 'Secondary structure', 'Tertiary structure', 'Quaternary structure', 'Primary structure', 'Primary structure is the linear sequence of amino acids encoded directly by the gene, forming the backbone of the polypeptide.', 710, 'Biochemistry'),
('Alpha-helices and beta-sheets are examples of which protein structure level?', 'Secondary structure', 'Primary structure', 'Tertiary structure', 'Quaternary structure', 'Secondary structure', 'Secondary structure describes local folding patterns stabilised by backbone hydrogen bonds, including alpha-helices and beta-pleated sheets.', 750, 'Biochemistry'),
('Which amino acid contains a sulfhydryl (-SH) group that can form disulfide bonds?', 'Cysteine', 'Methionine', 'Serine', 'Threonine', 'Cysteine', 'Cysteine''s thiol (-SH) group can be oxidised to form disulfide (-S-S-) bonds that stabilise protein tertiary structure.', 820, 'Biochemistry'),
('Haemoglobin is an example of which level of protein structure?', 'Quaternary structure', 'Primary structure', 'Secondary structure', 'Tertiary structure', 'Quaternary structure', 'Quaternary structure describes the arrangement of multiple polypeptide subunits; haemoglobin consists of two alpha and two beta subunits.', 780, 'Biochemistry'),
('Which amino acid is unique because its side chain is incorporated into the peptide backbone, constraining phi/psi angles?', 'Proline', 'Glycine', 'Alanine', 'Valine', 'Proline', 'Proline''s side chain forms a ring with its own backbone nitrogen, restricting rotation and often disrupting secondary structures such as alpha-helices.', 1200, 'Biochemistry'),
('The isoelectric point (pI) of an amino acid is the pH at which its net charge is:', 'Zero', 'Positive', 'Negative', 'Equal to its pKa', 'Zero', 'At the isoelectric point, an amino acid carries equal positive and negative charges, making its overall net charge zero.', 960, 'Biochemistry'),
-- ENZYMES & KINETICS --
('In Michaelis-Menten kinetics, Km is defined as the substrate concentration at which reaction velocity equals:', 'Vmax/2', 'Vmax', '2Vmax', 'Vmax/4', 'Vmax/2', 'Km (the Michaelis constant) is the substrate concentration at which the reaction velocity is exactly half of the maximum velocity (Vmax).', 1050, 'Biochemistry'),
('A competitive inhibitor of an enzyme will:', 'Increase the apparent Km without changing Vmax', 'Decrease Km without changing Vmax', 'Decrease both Km and Vmax', 'Increase both Km and Vmax', 'Increase the apparent Km without changing Vmax', 'Competitive inhibitors compete with substrate for the active site, raising apparent Km, but Vmax is still achievable at sufficiently high substrate concentrations.', 1150, 'Biochemistry'),
('A non-competitive inhibitor affects enzyme activity by:', 'Decreasing Vmax without changing Km', 'Increasing Km without changing Vmax', 'Increasing Vmax without changing Km', 'Decreasing both Km and Vmax', 'Decreasing Vmax without changing Km', 'Non-competitive inhibitors bind at an allosteric site regardless of substrate occupancy, reducing Vmax but not affecting substrate binding affinity (Km unchanged).', 1350, 'Biochemistry'),
('Which plot linearises Michaelis-Menten data as 1/v vs 1/[S]?', 'Lineweaver-Burk plot', 'Scatchard plot', 'Hill plot', 'Eadie-Hofstee plot', 'Lineweaver-Burk plot', 'The Lineweaver-Burk (double-reciprocal) plot graphs 1/v against 1/[S], yielding a straight line with slope Km/Vmax and y-intercept 1/Vmax.', 1100, 'Biochemistry'),
('Which of the following best describes an allosteric enzyme?', 'Activity is regulated by molecules binding at a site other than the active site', 'Activity depends solely on substrate concentration', 'It is irreversibly inhibited by competitive inhibitors', 'It follows strict Michaelis-Menten kinetics', 'Activity is regulated by molecules binding at a site other than the active site', 'Allosteric enzymes possess regulatory sites distinct from the active site; effector binding induces conformational changes that modulate activity.', 1000, 'Biochemistry'),
-- CARBOHYDRATES --
('Which sugar is the primary fuel for most mammalian cells?', 'Glucose', 'Fructose', 'Galactose', 'Ribose', 'Glucose', 'Glucose is the principal metabolic fuel oxidised by glycolysis and the citric acid cycle to generate ATP in most mammalian tissues.', 720, 'Biochemistry'),
('The bond linking glucose units in glycogen is primarily:', 'Alpha-1,4-glycosidic bond', 'Beta-1,4-glycosidic bond', 'Alpha-1,6-glycosidic bond', 'Beta-1,2-glycosidic bond', 'Alpha-1,4-glycosidic bond', 'Glycogen''s linear chains are connected by alpha-1,4-glycosidic bonds, with alpha-1,6 bonds at the branch points.', 980, 'Biochemistry'),
('Cellulose differs from starch in that it contains:', 'Beta-1,4-glycosidic bonds between glucose residues', 'Alpha-1,4-glycosidic bonds', 'Alpha-1,6-glycosidic bonds', 'Beta-1,6-glycosidic bonds', 'Beta-1,4-glycosidic bonds between glucose residues', 'Cellulose uses beta-1,4-glycosidic bonds, giving the polymer a rigid, linear structure that humans cannot digest due to lacking beta-glucosidase.', 1050, 'Biochemistry'),
('Which monosaccharide is NOT a hexose?', 'Ribose', 'Glucose', 'Fructose', 'Galactose', 'Ribose', 'Ribose is a pentose (5-carbon sugar) that forms the backbone of RNA, whereas glucose, fructose, and galactose are all hexoses.', 810, 'Biochemistry'),
-- GLYCOLYSIS --
('Glycolysis converts one glucose molecule into how many pyruvate molecules?', 'Two', 'One', 'Three', 'Four', 'Two', 'Glycolysis splits the 6-carbon glucose into two 3-carbon pyruvate molecules with a net yield of 2 ATP and 2 NADH.', 730, 'Biochemistry'),
('Which enzyme catalyses the committed step of glycolysis?', 'Phosphofructokinase-1 (PFK-1)', 'Hexokinase', 'Pyruvate kinase', 'Aldolase', 'Phosphofructokinase-1 (PFK-1)', 'PFK-1 catalyses the phosphorylation of fructose-6-phosphate to fructose-1,6-bisphosphate and is the major regulatory (committed) step of glycolysis.', 1100, 'Biochemistry'),
('What is the net ATP yield from the complete glycolysis of one glucose molecule under anaerobic conditions?', '2 ATP', '4 ATP', '36 ATP', '38 ATP', '2 ATP', 'Glycolysis consumes 2 ATP in the investment phase and generates 4 ATP in the payoff phase, for a net yield of 2 ATP per glucose.', 850, 'Biochemistry'),
('During anaerobic glycolysis in muscle, pyruvate is converted to:', 'Lactate', 'Ethanol', 'Acetyl-CoA', 'Oxaloacetate', 'Lactate', 'Under anaerobic conditions, lactate dehydrogenase reduces pyruvate to lactate, regenerating NAD+ so that glycolysis can continue.', 900, 'Biochemistry'),
-- CITRIC ACID (KREBS) CYCLE --
('The citric acid cycle occurs in which cellular compartment?', 'Mitochondrial matrix', 'Cytoplasm', 'Intermembrane space', 'Endoplasmic reticulum', 'Mitochondrial matrix', 'All enzymes of the citric acid cycle are located in the mitochondrial matrix, except succinate dehydrogenase which is embedded in the inner membrane.', 870, 'Biochemistry'),
('Which compound is regenerated at the end of each turn of the citric acid cycle?', 'Oxaloacetate', 'Citrate', 'Isocitrate', 'Succinate', 'Oxaloacetate', 'Oxaloacetate is the 4-carbon acceptor molecule that condenses with acetyl-CoA at the start of each cycle and is regenerated by the end.', 940, 'Biochemistry'),
('How many NADH molecules are produced per turn of the citric acid cycle?', '3', '1', '2', '4', '3', 'Each turn of the citric acid cycle yields 3 NADH (from isocitrate dehydrogenase, alpha-ketoglutarate dehydrogenase, and malate dehydrogenase reactions).', 1050, 'Biochemistry'),
('Which step of the citric acid cycle is catalysed by succinate dehydrogenase and directly linked to the electron transport chain?', 'Succinate to fumarate', 'Citrate to isocitrate', 'Malate to oxaloacetate', 'Alpha-ketoglutarate to succinyl-CoA', 'Succinate to fumarate', 'Succinate dehydrogenase (Complex II) oxidises succinate to fumarate, transferring electrons directly to FAD and then to ubiquinone in the ETC.', 1400, 'Biochemistry'),
-- OXIDATIVE PHOSPHORYLATION & ETC --
('The final electron acceptor in the mitochondrial electron transport chain is:', 'Molecular oxygen (O2)', 'NAD+', 'FAD', 'Cytochrome c', 'Molecular oxygen (O2)', 'Oxygen accepts the electrons at Complex IV (cytochrome c oxidase) and is reduced to water, completing the electron transport chain.', 810, 'Biochemistry'),
('According to the chemiosmotic theory, ATP synthase is driven by:', 'A proton gradient across the inner mitochondrial membrane', 'A sodium ion gradient', 'Direct transfer of electrons from NADH', 'Substrate-level phosphorylation', 'A proton gradient across the inner mitochondrial membrane', 'Peter Mitchell''s chemiosmotic theory states that electron transport pumps protons into the intermembrane space, and their flow back through ATP synthase (Complex V) drives ATP synthesis.', 1000, 'Biochemistry'),
('Approximately how many ATP molecules are produced from the complete oxidation of one glucose molecule via aerobic respiration?', '30-32 ATP', '2 ATP', '4 ATP', '38 ATP exactly', '30-32 ATP', 'Modern estimates give 30-32 ATP per glucose via coupled glycolysis, pyruvate oxidation, the citric acid cycle, and oxidative phosphorylation, accounting for mitochondrial membrane transport costs.', 1200, 'Biochemistry'),
('Which complex of the electron transport chain is inhibited by cyanide?', 'Complex IV (cytochrome c oxidase)', 'Complex I (NADH dehydrogenase)', 'Complex II (succinate dehydrogenase)', 'Complex III (cytochrome bc1)', 'Complex IV (cytochrome c oxidase)', 'Cyanide binds to the ferric iron (Fe3+) of cytochrome a3 in Complex IV, blocking electron transfer to oxygen and halting ATP production.', 1500, 'Biochemistry'),
-- GLUCONEOGENESIS --
('Gluconeogenesis is primarily carried out in which organ?', 'Liver', 'Skeletal muscle', 'Brain', 'Adipose tissue', 'Liver', 'The liver is the dominant site of gluconeogenesis, responsible for maintaining blood glucose during fasting; the kidney cortex contributes during prolonged starvation.', 870, 'Biochemistry'),
('Which enzyme bypasses the irreversible pyruvate kinase step in gluconeogenesis?', 'Pyruvate carboxylase and PEPCK', 'Phosphoglycerate kinase', 'Enolase', 'Phosphoglycerate mutase', 'Pyruvate carboxylase and PEPCK', 'Pyruvate carboxylase converts pyruvate to oxaloacetate, and PEPCK (phosphoenolpyruvate carboxykinase) converts it to PEP, bypassing the irreversible pyruvate kinase reaction.', 1450, 'Biochemistry'),
('Gluconeogenesis is stimulated by which hormone?', 'Glucagon', 'Insulin', 'Leptin', 'Aldosterone', 'Glucagon', 'Glucagon, secreted during fasting, activates adenylyl cyclase and PKA signalling that upregulates gluconeogenic enzymes and downregulates glycolysis.', 1100, 'Biochemistry'),
-- GLYCOGEN METABOLISM --
('Glycogen phosphorylase cleaves glucose residues from glycogen by:', 'Phosphorolysis, releasing glucose-1-phosphate', 'Hydrolysis, releasing free glucose', 'Oxidation, releasing gluconate', 'Transamination, releasing glucosamine', 'Phosphorolysis, releasing glucose-1-phosphate', 'Glycogen phosphorylase catalyses phosphorolytic cleavage of alpha-1,4-glycosidic bonds, releasing glucose-1-phosphate that enters glycolysis.', 1300, 'Biochemistry'),
('Which enzyme adds glucose units to the non-reducing end of glycogen during synthesis?', 'Glycogen synthase', 'Glycogen phosphorylase', 'Branching enzyme', 'Debranching enzyme', 'Glycogen synthase', 'Glycogen synthase transfers glucose from UDP-glucose to the non-reducing end of glycogen chains, forming alpha-1,4-glycosidic bonds.', 1000, 'Biochemistry'),
-- LIPIDS & MEMBRANES --
('The fluid mosaic model describes the plasma membrane as:', 'A phospholipid bilayer with embedded proteins that can move laterally', 'A rigid phospholipid bilayer', 'A single layer of lipids with proteins on one side only', 'A protein bilayer with embedded lipids', 'A phospholipid bilayer with embedded proteins that can move laterally', 'Singer and Nicolson''s fluid mosaic model proposes that proteins are embedded in or associated with a dynamic, fluid phospholipid bilayer in which both lipids and proteins can diffuse laterally.', 950, 'Biochemistry'),
('Fatty acid oxidation (beta-oxidation) occurs in which cellular location?', 'Mitochondrial matrix', 'Cytoplasm', 'Smooth endoplasmic reticulum', 'Peroxisome only', 'Mitochondrial matrix', 'Beta-oxidation of long-chain fatty acids takes place in the mitochondrial matrix after transport via the carnitine shuttle; very-long-chain fatty acids are also oxidised in peroxisomes.', 1050, 'Biochemistry'),
('Which product of fatty acid synthesis is the immediate precursor of all fatty acids?', 'Malonyl-CoA', 'Acetyl-CoA', 'Succinyl-CoA', 'Propionyl-CoA', 'Malonyl-CoA', 'Acetyl-CoA carboxylase converts acetyl-CoA to malonyl-CoA, which is the two-carbon donor used by fatty acid synthase in each elongation cycle.', 1250, 'Biochemistry'),
('Which fatty acid is considered essential because humans cannot synthesise it?', 'Linoleic acid (18:2, omega-6)', 'Palmitic acid (16:0)', 'Stearic acid (18:0)', 'Oleic acid (18:1)', 'Linoleic acid (18:2, omega-6)', 'Linoleic acid is an essential fatty acid because humans lack the delta-12 desaturase needed to introduce a double bond beyond carbon 9 from the carboxyl end.', 1350, 'Biochemistry'),
-- NUCLEIC ACIDS --
('The nitrogenous bases adenine and guanine are classified as:', 'Purines', 'Pyrimidines', 'Nucleosides', 'Nucleotides', 'Purines', 'Adenine and guanine are double-ringed purine bases, whereas cytosine, thymine, and uracil are single-ringed pyrimidines.', 760, 'Biochemistry'),
('In DNA, adenine pairs with thymine via how many hydrogen bonds?', 'Two', 'One', 'Three', 'Four', 'Two', 'Adenine forms two hydrogen bonds with thymine in DNA; in contrast, guanine and cytosine are held together by three hydrogen bonds.', 850, 'Biochemistry'),
('The 3'' to 5'' exonuclease activity of DNA polymerase I primarily serves as:', 'Proofreading to remove mismatched bases', 'A primer synthesis function', 'A nick translation activity', 'An RNA degradation function', 'Proofreading to remove mismatched bases', 'The 3'' to 5'' exonuclease activity of DNA polymerase allows it to excise incorrectly paired nucleotides during replication, greatly increasing fidelity.', 1300, 'Biochemistry'),
-- FATTY ACID OXIDATION --
('Each cycle of beta-oxidation of a saturated fatty acid yields:', '1 acetyl-CoA, 1 NADH, and 1 FADH2', '2 acetyl-CoA, 1 NADH, and 1 FADH2', '1 acetyl-CoA, 2 NADH, and 1 FADH2', '1 acetyl-CoA, 1 NADH, and 2 FADH2', '1 acetyl-CoA, 1 NADH, and 1 FADH2', 'Each round of beta-oxidation cleaves a 2-carbon unit as acetyl-CoA and reduces one FAD to FADH2 and one NAD+ to NADH.', 1200, 'Biochemistry'),
('Transport of long-chain fatty acids into the mitochondria requires:', 'Carnitine shuttle', 'Malate-aspartate shuttle', 'Citrate shuttle', 'Glycerol-3-phosphate shuttle', 'Carnitine shuttle', 'Long-chain acyl groups are converted to acylcarnitine by carnitine palmitoyltransferase I (CPT-I) on the outer membrane and transported into the mitochondrial matrix.', 1150, 'Biochemistry'),
-- AMINO ACID METABOLISM & UREA CYCLE --
('The urea cycle converts toxic ammonium ions into urea; where does the urea cycle primarily occur?', 'Liver', 'Kidney', 'Small intestine', 'Skeletal muscle', 'Liver', 'The urea cycle is located primarily in liver hepatocytes; the initial steps occur in the mitochondrial matrix and the remainder in the cytoplasm.', 920, 'Biochemistry'),
('Which amino acid carries nitrogen from peripheral tissues to the liver for disposal?', 'Alanine', 'Glutamate', 'Aspartate', 'Lysine', 'Alanine', 'The glucose-alanine cycle shuttles nitrogen from muscle to liver: transamination produces alanine, which is taken up by the liver, deaminated, and the carbon skeleton used for gluconeogenesis.', 1350, 'Biochemistry'),
('Phenylketonuria (PKU) results from a deficiency of which enzyme?', 'Phenylalanine hydroxylase', 'Homogentisate oxidase', 'Tyrosinase', 'DOPA decarboxylase', 'Phenylalanine hydroxylase', 'PKU is caused by deficient phenylalanine hydroxylase, which converts phenylalanine to tyrosine; accumulation of phenylalanine and its metabolites causes intellectual disability.', 1100, 'Biochemistry'),
-- VITAMINS, COFACTORS & COENZYMES --
('NAD+ (nicotinamide adenine dinucleotide) is derived from which vitamin?', 'Niacin (vitamin B3)', 'Riboflavin (vitamin B2)', 'Thiamine (vitamin B1)', 'Pyridoxine (vitamin B6)', 'Niacin (vitamin B3)', 'NAD+ and NADP+ are synthesised from niacin (nicotinic acid or nicotinamide, vitamin B3) and serve as major electron carriers in metabolism.', 980, 'Biochemistry'),
('FAD (flavin adenine dinucleotide) is synthesised from which vitamin?', 'Riboflavin (vitamin B2)', 'Niacin (vitamin B3)', 'Cobalamin (vitamin B12)', 'Ascorbic acid (vitamin C)', 'Riboflavin (vitamin B2)', 'FAD and FMN are both derived from riboflavin (vitamin B2) and function as cofactors for oxidoreductases including succinate dehydrogenase and fatty acyl-CoA dehydrogenase.', 1000, 'Biochemistry'),
('Coenzyme A (CoA) is derived from which vitamin?', 'Pantothenic acid (vitamin B5)', 'Biotin (vitamin B7)', 'Thiamine (vitamin B1)', 'Pyridoxine (vitamin B6)', 'Pantothenic acid (vitamin B5)', 'Coenzyme A contains a pantothenic acid (vitamin B5) unit and is essential for acyl group activation in fatty acid oxidation, the citric acid cycle, and fatty acid synthesis.', 1050, 'Biochemistry'),
-- BIOENERGETICS --
('A reaction is thermodynamically spontaneous when its standard Gibbs free energy change (DeltaG degrees) is:', 'Negative', 'Positive', 'Zero', 'Equal to the activation energy', 'Negative', 'A negative DeltaG (exergonic reaction) indicates spontaneous release of free energy; a positive DeltaG (endergonic) requires energy input to proceed.', 870, 'Biochemistry'),
('The hydrolysis of ATP releases energy primarily because:', 'Products (ADP + Pi) have lower free energy than ATP', 'ATP has a high activation energy', 'Hydrolysis increases the number of phosphate groups', 'ADP is a stronger acid than ATP', 'Products (ADP + Pi) have lower free energy than ATP', 'ATP is a high-energy compound because electrostatic repulsion between phosphate groups and resonance stabilisation of products make hydrolysis highly exergonic (DeltaG degrees approx -30.5 kJ/mol).', 1000, 'Biochemistry'),
-- PENTOSE PHOSPHATE PATHWAY --
('The primary purpose of the oxidative phase of the pentose phosphate pathway is to produce:', 'NADPH and ribose-5-phosphate', 'NADH and pyruvate', 'ATP and oxaloacetate', 'FADH2 and acetyl-CoA', 'NADPH and ribose-5-phosphate', 'The oxidative pentose phosphate pathway generates NADPH (for reductive biosynthesis and antioxidant defence) and ribose-5-phosphate (for nucleotide synthesis).', 1100, 'Biochemistry'),
('Glucose-6-phosphate dehydrogenase (G6PD) deficiency causes haemolytic anaemia because red blood cells cannot adequately produce:', 'NADPH to regenerate glutathione', 'ATP via glycolysis', 'Haemoglobin', 'Glucose-1-phosphate', 'NADPH to regenerate glutathione', 'G6PD is the entry enzyme of the pentose phosphate pathway; without NADPH, reduced glutathione cannot be maintained, leading to oxidative damage and lysis of erythrocytes.', 1500, 'Biochemistry'),
-- METABOLIC REGULATION --
('Insulin stimulates glycogen synthesis by activating:', 'Protein phosphatase 1, which activates glycogen synthase', 'Glycogen phosphorylase kinase', 'Adenylyl cyclase', 'Protein kinase A', 'Protein phosphatase 1, which activates glycogen synthase', 'Insulin signalling activates protein phosphatase 1, which dephosphorylates and thereby activates glycogen synthase while simultaneously inactivating glycogen phosphorylase.', 1600, 'Biochemistry'),
('AMP is an allosteric activator of PFK-1 and an inhibitor of fructose-1,6-bisphosphatase, effectively:', 'Stimulating glycolysis and inhibiting gluconeogenesis simultaneously', 'Inhibiting both glycolysis and gluconeogenesis', 'Stimulating gluconeogenesis only', 'Having no net metabolic effect', 'Stimulating glycolysis and inhibiting gluconeogenesis simultaneously', 'High AMP signals low energy; it activates PFK-1 to accelerate ATP production via glycolysis and inhibits fructose-1,6-bisphosphatase to prevent futile cycling with gluconeogenesis.', 1750, 'Biochemistry');
