-- 50 additional Discrete Mathematics exam questions
-- Covers: set theory, logic, proofs, combinatorics, recurrences, number theory,
--         relations, functions, graph theory, Boolean algebra, complexity
INSERT INTO discretemath (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
-- ── SET THEORY (5) ───────────────────────────────────────────────────────────
('How many elements are in the power set of a set with 4 elements?', '16', '8', '4', '32', '16', 'The power set of an n-element set has 2^n elements; 2^4 = 16.', 760, 'DiscreteMath'),
('If |A| = 10, |B| = 8, and |A ∩ B| = 3, what is |A ∪ B|?', '15', '18', '21', '13', '15', 'Inclusion-exclusion: |A ∪ B| = |A| + |B| - |A ∩ B| = 10 + 8 - 3 = 15.', 780, 'DiscreteMath'),
('Which of the following is the complement of A ∪ B (relative to universal set U)?', 'A'' ∩ B''', 'A'' ∪ B''', 'A ∩ B', 'A ∪ B''', 'A'' ∩ B''', 'De Morgan''s law: (A ∪ B)'' = A'' ∩ B''. The complement of a union is the intersection of complements.', 820, 'DiscreteMath'),
('A relation R on set A is an equivalence relation if it is reflexive, symmetric, and which third property?', 'Transitive', 'Antisymmetric', 'Asymmetric', 'Total', 'Transitive', 'An equivalence relation requires reflexivity (aRa), symmetry (aRb => bRa), and transitivity (aRb and bRc => aRc).', 900, 'DiscreteMath'),
('The Cartesian product A × B of sets A = {1,2} and B = {a,b} has how many elements?', '4', '2', '6', '8', '4', 'A × B contains all ordered pairs (a,b) with a in A, b in B. |A × B| = |A| * |B| = 2 * 2 = 4.', 740, 'DiscreteMath'),
-- ── LOGIC – PROPOSITIONAL (6) ────────────────────────────────────────────────
('Which logical connective produces TRUE only when both operands are TRUE?', 'AND (conjunction)', 'OR (disjunction)', 'NOT (negation)', 'XOR (exclusive or)', 'AND (conjunction)', 'The conjunction P ∧ Q is TRUE exactly when both P and Q are TRUE; any FALSE operand makes it FALSE.', 710, 'DiscreteMath'),
('What is the contrapositive of the statement "If P then Q"?', 'If not Q then not P', 'If Q then P', 'If not P then not Q', 'Not P or Q', 'If not Q then not P', 'The contrapositive of P => Q is ¬Q => ¬P, and it is logically equivalent to the original statement.', 800, 'DiscreteMath'),
('Which of the following is a tautology?', 'P ∨ ¬P', 'P ∧ ¬P', 'P => P ∧ Q', 'P => Q', 'P ∨ ¬P', 'P ∨ ¬P is the law of excluded middle — it is TRUE for every truth-value assignment, making it a tautology.', 760, 'DiscreteMath'),
('In a truth table for P => Q, which row has the value FALSE?', 'P = TRUE, Q = FALSE', 'P = FALSE, Q = TRUE', 'P = FALSE, Q = FALSE', 'P = TRUE, Q = TRUE', 'P = TRUE, Q = FALSE', 'An implication P => Q is FALSE only when the hypothesis P is TRUE and the conclusion Q is FALSE.', 820, 'DiscreteMath'),
('Which equivalence is known as the Distributive Law in propositional logic?', 'P ∧ (Q ∨ R) <=> (P ∧ Q) ∨ (P ∧ R)', 'P ∧ (Q ∧ R) <=> (P ∧ Q) ∧ R', '¬(P ∧ Q) <=> ¬P ∨ ¬Q', 'P ∨ (P ∧ Q) <=> P', 'P ∧ (Q ∨ R) <=> (P ∧ Q) ∨ (P ∧ R)', 'The distributive law states that AND distributes over OR: P ∧ (Q ∨ R) <=> (P ∧ Q) ∨ (P ∧ R).', 880, 'DiscreteMath'),
('What does the universal quantifier ∀x P(x) mean?', 'P(x) is true for every x in the domain', 'There exists at least one x for which P(x) is true', 'P(x) is true for exactly one x', 'P(x) is sometimes true', 'P(x) is true for every x in the domain', '∀x P(x) asserts that the predicate P holds for all elements x in the given domain.', 790, 'DiscreteMath'),
-- ── PROOF TECHNIQUES (4) ─────────────────────────────────────────────────────
('In a proof by contradiction, you assume what to begin?', 'The negation of what you want to prove', 'The statement you want to prove', 'An arbitrary hypothesis', 'The base case', 'The negation of what you want to prove', 'Proof by contradiction (reductio ad absurdum) assumes ¬P and derives a logical contradiction, proving P must be true.', 850, 'DiscreteMath'),
('What does the inductive step in mathematical induction prove?', 'If the statement holds for k, it holds for k+1', 'The statement holds for k = 0', 'The statement holds for all even integers', 'The statement has a counterexample', 'If the statement holds for k, it holds for k+1', 'The inductive step establishes P(k) => P(k+1). Together with the base case this implies P(n) for all n >= base.', 870, 'DiscreteMath'),
('Prove that sqrt(2) is irrational. Which method is typically used?', 'Proof by contradiction', 'Proof by exhaustion', 'Proof by construction', 'Direct proof', 'Proof by contradiction', 'Assume sqrt(2) = p/q in lowest terms, square both sides to get 2q^2 = p^2, derive that both p and q are even — contradicting lowest terms.', 1050, 'DiscreteMath'),
('Strong induction differs from regular induction in that the inductive hypothesis assumes what?', 'The statement holds for all values up to k', 'The statement holds only for k', 'The statement holds for k-1 only', 'The statement holds for the base case only', 'The statement holds for all values up to k', 'Strong (complete) induction assumes P(1), P(2), ..., P(k) are all true before proving P(k+1), giving more power when needed.', 1100, 'DiscreteMath'),
-- ── COMBINATORICS (8) ────────────────────────────────────────────────────────
('In how many ways can 5 distinct books be arranged on a shelf?', '120', '60', '25', '24', '120', 'This is a permutation of 5 objects: 5! = 5 * 4 * 3 * 2 * 1 = 120.', 750, 'DiscreteMath'),
('What does C(n, k) = C(n, n-k) illustrate?', 'Symmetry of binomial coefficients', 'Pascal''s identity', 'The binomial theorem', 'Stars and bars', 'Symmetry of binomial coefficients', 'Choosing k items from n is the same as leaving out n-k items, so C(n,k) = C(n,n-k) — the symmetry property.', 810, 'DiscreteMath'),
('The Pigeonhole Principle states that if n+1 items are placed in n containers, at least one container holds how many items?', 'At least 2', 'At most 2', 'Exactly 2', 'At least n', 'At least 2', 'Pigeonhole: if more items than containers, some container must hold at least 2 items. Formally: at least ceil((n+1)/n) = 2.', 870, 'DiscreteMath'),
('What is the coefficient of x^3 * y^2 in the expansion of (x + y)^5?', '10', '20', '5', '15', '10', 'By the binomial theorem, the coefficient of x^3 y^2 in (x+y)^5 is C(5,2) = C(5,3) = 10.', 950, 'DiscreteMath'),
('How many 3-digit numbers can be formed using digits 1-9 if repetition is allowed?', '729', '504', '84', '512', '729', 'Each of the 3 positions has 9 choices (1-9), so the total is 9^3 = 729.', 780, 'DiscreteMath'),
('Stars and bars gives the number of ways to distribute k identical items into n distinct bins (allowing empty bins) as?', 'C(k+n-1, n-1)', 'C(k, n)', 'n^k', 'k! / n!', 'C(k+n-1, n-1)', 'The stars-and-bars formula counts weak compositions: C(k+n-1, n-1) ways to put k identical items into n bins.', 1150, 'DiscreteMath'),
('A committee of 4 is chosen from 6 men and 5 women. How many committees have exactly 2 women?', '150', '60', '90', '120', '150', 'Choose 2 women from 5: C(5,2)=10; choose 2 men from 6: C(6,2)=15; by multiplication rule total = 10*15 = 150.', 1050, 'DiscreteMath'),
('How many strings of length 4 over the alphabet {0, 1} have exactly two 1s?', '6', '4', '8', '12', '6', 'Choose 2 positions out of 4 for the 1s: C(4,2) = 6. The remaining positions are 0.', 880, 'DiscreteMath'),
-- ── RECURRENCE RELATIONS (3) ─────────────────────────────────────────────────
('What is the closed-form solution to the recurrence T(n) = 2*T(n-1) with T(0) = 1?', '2^n', 'n^2', '2n', 'n!', '2^n', 'Unrolling: T(n) = 2*T(n-1) = 2^2*T(n-2) = ... = 2^n*T(0) = 2^n.', 1000, 'DiscreteMath'),
('The recurrence a(n) = a(n-1) + a(n-2) with a(0)=0 and a(1)=1 generates which sequence?', 'Fibonacci sequence', 'Arithmetic sequence', 'Geometric sequence', 'Lucas numbers', 'Fibonacci sequence', 'Starting from 0, 1, each term is the sum of the two before: 0,1,1,2,3,5,8,... — the Fibonacci sequence.', 870, 'DiscreteMath'),
('By the Master Theorem, T(n) = 4*T(n/2) + n has solution?', 'O(n^2)', 'O(n log n)', 'O(n)', 'O(n^3)', 'O(n^2)', 'Here a=4, b=2, f(n)=n. log_b(a)=log_2(4)=2. Since f(n) = O(n^(2-1)), Case 1 applies: T(n) = Theta(n^2).', 1500, 'DiscreteMath'),
-- ── NUMBER THEORY (5) ────────────────────────────────────────────────────────
('What is 17 mod 5?', '2', '3', '1', '4', '2', '17 = 3*5 + 2, so 17 mod 5 = 2.', 720, 'DiscreteMath'),
('What is gcd(48, 18) computed by the Euclidean algorithm?', '6', '9', '3', '12', '6', '48 = 2*18+12; 18 = 1*12+6; 12 = 2*6+0. The last non-zero remainder is gcd = 6.', 850, 'DiscreteMath'),
('Fermat''s Little Theorem states that if p is prime and gcd(a,p)=1, then?', 'a^(p-1) ≡ 1 (mod p)', 'a^p ≡ a (mod p-1)', 'a^p ≡ 0 (mod p)', 'a^2 ≡ 1 (mod p)', 'a^(p-1) ≡ 1 (mod p)', 'Fermat''s Little Theorem: for prime p and a not divisible by p, a^(p-1) ≡ 1 (mod p). Used in RSA and primality tests.', 1300, 'DiscreteMath'),
('Which of the following is NOT a prime number?', '91', '97', '89', '83', '91', '91 = 7 * 13, so it is composite. 83, 89, and 97 are all prime.', 900, 'DiscreteMath'),
('The equation ax ≡ b (mod n) has a solution if and only if what condition holds?', 'gcd(a, n) divides b', 'a divides b', 'n divides b', 'gcd(a, b) = 1', 'gcd(a, n) divides b', 'Linear congruence ax ≡ b (mod n) is solvable iff gcd(a,n) | b, by the theory of Bezout identities.', 1250, 'DiscreteMath'),
-- ── RELATIONS & FUNCTIONS (5) ────────────────────────────────────────────────
('A function f: A -> B is injective (one-to-one) if?', 'f(x1) = f(x2) implies x1 = x2', 'Every element of B is mapped to', 'f is its own inverse', 'f maps each x to exactly one y', 'f(x1) = f(x2) implies x1 = x2', 'Injectivity: distinct inputs give distinct outputs. f(x1)=f(x2) => x1=x2 (equivalently, no two elements share an image).', 870, 'DiscreteMath'),
('A function f: A -> B is surjective (onto) if?', 'Every element of B has at least one pre-image in A', 'No two elements of A map to the same element of B', 'f has an inverse', 'A and B have the same cardinality', 'Every element of B has at least one pre-image in A', 'Surjectivity means the range equals the codomain B — for every b in B there exists a in A with f(a)=b.', 890, 'DiscreteMath'),
('How many different functions exist from a 3-element set to a 2-element set?', '8', '6', '9', '3', '8', 'Each of the 3 elements of the domain can independently map to any of 2 elements: 2^3 = 8 functions.', 920, 'DiscreteMath'),
('Which of the following relations on {1,2,3} is a partial order?', 'R = {(1,1),(2,2),(3,3),(1,2),(2,3),(1,3)}', 'R = {(1,2),(2,1)}', 'R = {(1,2),(2,3),(3,1)}', 'R = {(1,2),(1,3)}', 'R = {(1,1),(2,2),(3,3),(1,2),(2,3),(1,3)}', 'A partial order is reflexive, antisymmetric, and transitive. The relation given includes the diagonal (reflexive) and satisfies the other conditions.', 1100, 'DiscreteMath'),
('What is the composition g ∘ f (x) if f(x) = x+1 and g(x) = 2x?', '2x + 2', '2x + 1', 'x + 2', '2x', '2x + 2', 'g ∘ f means apply f first, then g: g(f(x)) = g(x+1) = 2(x+1) = 2x+2.', 830, 'DiscreteMath'),
-- ── GRAPH THEORY (8) ─────────────────────────────────────────────────────────
('What is the degree of a vertex in a graph?', 'The number of edges incident to it', 'The number of vertices connected to it by paths', 'Its label in the graph', 'Its distance from vertex 1', 'The number of edges incident to it', 'The degree of a vertex is the count of edges touching it. A loop contributes 2 to the degree.', 730, 'DiscreteMath'),
('The Handshaking Lemma states that for any graph, the sum of all vertex degrees equals?', '2 * |E|', '|E|', '|V| * |E|', '|V|^2', '2 * |E|', 'Every edge contributes 1 to each of its two endpoint degrees, so the total degree sum = 2|E|.', 820, 'DiscreteMath'),
('A tree with n vertices has exactly how many edges?', 'n - 1', 'n', 'n + 1', 'n * (n-1) / 2', 'n - 1', 'A tree is a connected acyclic graph. By the tree property, every tree on n vertices has exactly n-1 edges.', 860, 'DiscreteMath'),
('An Euler circuit in a connected graph exists if and only if every vertex has what property?', 'Even degree', 'Odd degree', 'Degree at least 2', 'Degree equal to |V|-1', 'Even degree', 'Euler''s theorem: a connected graph has an Euler circuit (traversing every edge exactly once) iff every vertex has even degree.', 1050, 'DiscreteMath'),
('A Hamiltonian path visits every vertex exactly once. What is the complexity of deciding if one exists?', 'NP-complete', 'O(n log n)', 'O(n^2)', 'Polynomial', 'NP-complete', 'The Hamiltonian path/cycle problem is NP-complete; no polynomial-time algorithm is known, unlike the Eulerian case.', 1450, 'DiscreteMath'),
('What is the minimum number of colors needed to properly color the vertices of a cycle C5 (5-cycle)?', '3', '2', '4', '5', '3', 'C5 is an odd cycle. Odd cycles require 3 colors because you cannot 2-color them without a conflict at the last edge.', 1100, 'DiscreteMath'),
('By Kuratowski''s theorem, a graph is planar if and only if it contains no subdivision of K5 or?', 'K3,3', 'K4', 'K6', 'K2,3', 'K3,3', 'Kuratowski''s theorem: a graph is planar iff it has no subgraph homeomorphic to K5 (complete on 5) or K3,3 (complete bipartite 3-3).', 1550, 'DiscreteMath'),
('In a bipartite graph, vertices can be divided into two sets such that every edge connects?', 'A vertex in one set to a vertex in the other set', 'Two vertices in the same set', 'Two vertices of equal degree', 'Adjacent vertices only', 'A vertex in one set to a vertex in the other set', 'A bipartite graph has vertex set V = X ∪ Y (disjoint) and every edge goes from X to Y — no edges within X or within Y.', 900, 'DiscreteMath'),
-- ── BOOLEAN ALGEBRA (4) ──────────────────────────────────────────────────────
('In Boolean algebra, the identity element for the AND operation is?', '1', '0', 'The variable itself', 'Its complement', '1', 'x AND 1 = x for all x. So 1 is the identity for AND, just as 0 is the identity for OR (x OR 0 = x).', 760, 'DiscreteMath'),
('Which Boolean law states that x AND (x OR y) = x?', 'Absorption law', 'Distributive law', 'De Morgan''s law', 'Associative law', 'Absorption law', 'The absorption law: x ∧ (x ∨ y) = x and x ∨ (x ∧ y) = x. The larger expression is "absorbed" by the simpler one.', 1000, 'DiscreteMath'),
('A Boolean function of n variables has how many possible input combinations?', '2^n', 'n^2', '2n', 'n!', '2^n', 'Each of n variables can be 0 or 1 independently, giving 2 * 2 * ... * 2 (n times) = 2^n possible inputs.', 810, 'DiscreteMath'),
('The NAND gate is called a universal gate because?', 'Any Boolean function can be built using only NAND gates', 'It is the fastest gate', 'It has the lowest power consumption', 'It implements both AND and OR directly', 'Any Boolean function can be built using only NAND gates', 'NAND is functionally complete: NOT, AND, and OR can each be expressed in NAND, so all Boolean functions can be realized.', 1150, 'DiscreteMath'),
-- ── COMPLEXITY & MISC (2) ────────────────────────────────────────────────────
('The class P consists of problems solvable in?', 'Polynomial time by a deterministic Turing machine', 'Polynomial time by a non-deterministic machine', 'Exponential time', 'Logarithmic space', 'Polynomial time by a deterministic Turing machine', 'P is the class of decision problems solvable in O(n^k) time for some constant k on a deterministic Turing machine.', 1200, 'DiscreteMath'),
('What does it mean when we say a binary relation R is antisymmetric?', 'If aRb and bRa then a = b', 'aRb implies bRa', 'aRb implies NOT bRa', 'R contains no pair (a,a)', 'If aRb and bRa then a = b', 'Antisymmetry: if both aRb and bRa hold then a must equal b. This is a key property of partial orders (e.g., <=).', 970, 'DiscreteMath');
