INSERT INTO physiology (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
-- Cell membrane transport (easy-medium)
('Which ion is primarily responsible for the rising phase of a neuron action potential?', 'Sodium (Na+)', 'Potassium (K+)', 'Chloride (Cl-)', 'Calcium (Ca2+)', 'Sodium (Na+)', 'Voltage-gated Na+ channels open rapidly, allowing Na+ influx that depolarises the membrane from -70 mV toward +30 mV.', 760, 'Physiology'),
('What type of transport moves glucose into intestinal epithelial cells against its concentration gradient using the Na+ gradient?', 'Secondary active transport', 'Primary active transport', 'Facilitated diffusion', 'Simple diffusion', 'Secondary active transport', 'SGLT1 co-transports Na+ and glucose; the Na+ gradient maintained by Na+/K+-ATPase drives glucose uptake against its gradient.', 950, 'Physiology'),
('Which protein is responsible for pumping 3 Na+ out and 2 K+ into the cell per ATP hydrolysed?', 'Na+/K+-ATPase', 'SERCA pump', 'H+/K+-ATPase', 'Calcium ATPase', 'Na+/K+-ATPase', 'Na+/K+-ATPase (the sodium-potassium pump) maintains the resting electrochemical gradients essential for neuronal excitability.', 820, 'Physiology'),
('Aquaporins are transmembrane channels that facilitate rapid movement of which molecule?', 'Water', 'Glucose', 'Sodium ions', 'Oxygen', 'Water', 'Aquaporins form water-selective pores in cell membranes, enabling rapid osmotic water flux without transporting solutes.', 700, 'Physiology'),

-- Neuron & action potentials (easy-medium-hard)
('What is the typical resting membrane potential of a mammalian neuron?', '-70 mV', '+30 mV', '0 mV', '-55 mV', '-70 mV', 'The resting membrane potential of ~-70 mV is maintained mainly by K+ leakage channels and the Na+/K+-ATPase.', 760, 'Physiology'),
('What determines the conduction velocity of an action potential most strongly in large myelinated axons?', 'Saltatory conduction between nodes of Ranvier', 'Diameter of the axon alone', 'Density of Na+ channels in the internodal segments', 'Amplitude of the action potential', 'Saltatory conduction between nodes of Ranvier', 'Myelin insulates the axon, forcing the action potential to jump between nodes of Ranvier, greatly increasing conduction speed.', 1200, 'Physiology'),
('During the absolute refractory period, a neuron cannot fire another action potential because:', 'Voltage-gated Na+ channels are inactivated', 'K+ channels are permanently closed', 'The membrane potential is too positive', 'All neurotransmitters are depleted', 'Voltage-gated Na+ channels are inactivated', 'Na+ channels enter an inactivated (closed but not activatable) state immediately after opening, making re-excitation impossible until they recover.', 1100, 'Physiology'),
('Which of the following correctly describes an EPSP?', 'A graded depolarisation that brings the membrane closer to threshold', 'A hyperpolarisation that inhibits firing', 'An all-or-none potential lasting 100 ms', 'A long-lasting K+ efflux', 'A graded depolarisation that brings the membrane closer to threshold', 'An excitatory postsynaptic potential (EPSP) is a small depolarisation caused by influx of cations, which increases the probability of firing.', 1050, 'Physiology'),

-- Synaptic transmission (medium-hard)
('At a chemical synapse, which event directly triggers exocytosis of neurotransmitter vesicles?', 'Influx of Ca2+ through voltage-gated Ca2+ channels', 'Influx of Na+ through voltage-gated Na+ channels', 'Binding of acetylcholine to postsynaptic receptors', 'Opening of presynaptic K+ channels', 'Influx of Ca2+ through voltage-gated Ca2+ channels', 'Depolarisation of the presynaptic terminal opens voltage-gated Ca2+ channels; Ca2+ entry triggers SNARE-mediated vesicle fusion.', 1150, 'Physiology'),
('Acetylcholine is broken down in the synaptic cleft by which enzyme?', 'Acetylcholinesterase', 'Monoamine oxidase', 'Catechol-O-methyltransferase', 'Phospholipase C', 'Acetylcholinesterase', 'Acetylcholinesterase rapidly hydrolyses acetylcholine into acetate and choline, terminating synaptic transmission.', 850, 'Physiology'),
('GABA is the primary inhibitory neurotransmitter in the CNS; its ionotropic receptor (GABA-A) is a channel permeable to which ion?', 'Cl-', 'K+', 'Na+', 'Ca2+', 'Cl-', 'GABA-A receptor activation opens a Cl- channel; Cl- influx hyperpolarises the postsynaptic neuron and reduces excitability.', 1300, 'Physiology'),
('Long-term potentiation (LTP) at hippocampal synapses requires the unblocking of which receptor by prior depolarisation?', 'NMDA receptor', 'AMPA receptor', 'GABA-B receptor', 'Muscarinic receptor', 'NMDA receptor', 'Mg2+ blocks the NMDA receptor channel at rest; membrane depolarisation displaces Mg2+, allowing Ca2+ influx that initiates LTP.', 1600, 'Physiology'),

-- Muscle contraction – sliding filament (easy-medium)
('In skeletal muscle, which protein covers the actin-binding site on thin filaments at rest?', 'Tropomyosin', 'Troponin C', 'Titin', 'Myosin heavy chain', 'Tropomyosin', 'At rest, tropomyosin sterically blocks myosin-binding sites on actin; Ca2+ binding to troponin C shifts tropomyosin to expose the sites.', 900, 'Physiology'),
('During a muscle twitch, Ca2+ is released from which intracellular compartment to initiate contraction?', 'Sarcoplasmic reticulum', 'Mitochondria', 'Nucleus', 'Golgi apparatus', 'Sarcoplasmic reticulum', 'The action potential travels down T-tubules and triggers Ca2+ release from the sarcoplasmic reticulum via ryanodine receptors.', 820, 'Physiology'),
('The power stroke of myosin cross-bridges is driven by release of which molecule from myosin?', 'Inorganic phosphate (Pi)', 'ADP', 'ATP', 'AMP', 'Inorganic phosphate (Pi)', 'After myosin binds actin in the cocked position, release of Pi triggers the power stroke; ADP is released afterwards.', 1350, 'Physiology'),
('Which zone of the sarcomere contains only thick filaments and shortens during contraction?', 'H zone', 'I band', 'A band', 'Z disc', 'H zone', 'The H zone is the central region of the A band containing only myosin; it narrows as actin slides inward during contraction.', 1050, 'Physiology'),

-- Cardiac physiology (medium-hard)
('Which cells in the heart have the fastest intrinsic pacemaker rate under normal conditions?', 'Sinoatrial (SA) node cells', 'Atrioventricular (AV) node cells', 'Purkinje fibres', 'Ventricular myocytes', 'Sinoatrial (SA) node cells', 'SA node cells depolarise spontaneously at ~60-100 bpm, the highest rate, so they dominate as the cardiac pacemaker.', 880, 'Physiology'),
('The Frank-Starling law of the heart states that stroke volume increases when:', 'Ventricular end-diastolic volume increases', 'Afterload increases', 'Heart rate decreases', 'Sympathetic tone decreases', 'Ventricular end-diastolic volume increases', 'Greater preload stretches myocardial fibres, increasing cross-bridge overlap and force of contraction, thereby increasing stroke volume.', 1100, 'Physiology'),
('On an ECG, which interval represents the time for ventricular depolarisation and repolarisation?', 'QT interval', 'PR interval', 'QRS duration', 'RR interval', 'QT interval', 'The QT interval spans from the onset of ventricular depolarisation (Q) to the end of repolarisation (T), reflecting total ventricular electrical activity.', 1200, 'Physiology'),
('During isovolumetric contraction in the cardiac cycle, both the mitral and aortic valves are:', 'Both closed', 'Both open', 'Mitral open, aortic closed', 'Mitral closed, aortic open', 'Both closed', 'Isovolumetric contraction begins when the mitral valve closes (rising pressure) and ends when pressure exceeds aortic diastolic pressure to open the aortic valve.', 1400, 'Physiology'),
('Which phase of the cardiac cycle is shortened first when heart rate increases?', 'Diastole', 'Systole', 'Isovolumetric contraction', 'Isovolumetric relaxation', 'Diastole', 'At higher heart rates, diastolic filling time is shortened disproportionately more than systole, which can reduce stroke volume at extreme rates.', 1550, 'Physiology'),

-- Vascular system & blood pressure regulation (medium-hard)
('Mean arterial pressure (MAP) is best approximated by which formula?', 'Diastolic BP + 1/3 (Pulse pressure)', 'Systolic BP + Diastolic BP / 2', 'Systolic BP - Diastolic BP', 'Diastolic BP x Heart rate', 'Diastolic BP + 1/3 (Pulse pressure)', 'Because diastole occupies ~2/3 of the cardiac cycle, MAP approximates DBP + 1/3(PP), or equivalently (SBP + 2xDBP)/3.', 1250, 'Physiology'),
('Baroreceptors in the carotid sinus and aortic arch respond to increased arterial pressure by:', 'Increasing parasympathetic output and decreasing sympathetic output to lower BP', 'Increasing sympathetic output to raise BP', 'Releasing renin from the juxtaglomerular apparatus', 'Stimulating the adrenal medulla to release adrenaline', 'Increasing parasympathetic output and decreasing sympathetic output to lower BP', 'Stretch-sensitive baroreceptors fire more rapidly when BP rises, triggering reflexes that slow heart rate and dilate vessels.', 1350, 'Physiology'),
('Arterioles are the primary site of vascular resistance because:', 'They have the greatest total cross-sectional resistance due to small radius', 'They contain the largest proportion of blood volume', 'They lack smooth muscle', 'They are closest to the heart', 'They have the greatest total cross-sectional resistance due to small radius', 'Resistance is proportional to 1/r^4 (Poiseuille''s law); arterioles'' small radii make them the dominant site of peripheral resistance control.', 1500, 'Physiology'),
('Angiotensin II raises blood pressure by all of the following EXCEPT:', 'Dilating afferent arterioles to increase GFR', 'Stimulating aldosterone release', 'Causing systemic vasoconstriction', 'Promoting Na+ reabsorption in the proximal tubule', 'Dilating afferent arterioles to increase GFR', 'Angiotensin II constricts both afferent and efferent arterioles (efferent more), which can reduce GFR; it does not dilate afferent arterioles.', 1700, 'Physiology'),

-- Respiratory physiology (easy-medium-hard)
('Oxygen is transported in the blood primarily as:', 'Oxyhaemoglobin', 'Dissolved in plasma', 'Carbamino compounds', 'Bound to albumin', 'Oxyhaemoglobin', 'About 98% of O2 in blood is bound to haemoglobin; only ~2% is dissolved in plasma.', 780, 'Physiology'),
('The Bohr effect describes a rightward shift of the oxyhaemoglobin dissociation curve caused by:', 'Increased CO2 and decreased pH', 'Decreased CO2 and increased pH', 'Increased temperature only', 'Decreased 2,3-DPG', 'Increased CO2 and decreased pH', 'Bohr effect: acidosis and high CO2 reduce haemoglobin''s O2 affinity, promoting O2 unloading in metabolically active tissues.', 1150, 'Physiology'),
('At the alveolar level, gas exchange occurs by which mechanism?', 'Simple diffusion down partial pressure gradients', 'Active transport via carrier proteins', 'Facilitated diffusion through aquaporins', 'Bulk flow driven by hydrostatic pressure', 'Simple diffusion down partial pressure gradients', 'O2 moves from high pO2 in alveoli (~100 mmHg) to lower pO2 in pulmonary capillaries; CO2 moves in the opposite direction.', 820, 'Physiology'),
('Hypercapnia (elevated arterial PCO2) stimulates ventilation primarily via which receptors?', 'Central chemoreceptors in the medulla sensing changes in CSF pH', 'Peripheral chemoreceptors sensing O2 directly', 'Baroreceptors in the carotid sinus', 'Pulmonary stretch receptors', 'Central chemoreceptors in the medulla sensing changes in CSF pH', 'CO2 crosses the blood-brain barrier and reacts with water to form H+, which stimulates central chemoreceptors to increase respiratory drive.', 1300, 'Physiology'),
('2,3-bisphosphoglycerate (2,3-DPG) shifts the oxyhaemoglobin dissociation curve to the right, which:', 'Decreases haemoglobin''s O2 affinity, facilitating O2 release to tissues', 'Increases haemoglobin''s O2 affinity, promoting O2 loading in the lungs', 'Has no effect at physiological pH', 'Only affects foetal haemoglobin', 'Decreases haemoglobin''s O2 affinity, facilitating O2 release to tissues', '2,3-DPG binds the deoxyhaemoglobin configuration, stabilising it and decreasing O2 affinity so tissues can extract O2 more readily.', 1600, 'Physiology'),
('Functional residual capacity (FRC) is the volume of air remaining in the lungs after:', 'A normal passive expiration', 'A maximal forced expiration', 'A maximal inspiration', 'A normal inspiration', 'A normal passive expiration', 'FRC = ERV + RV; it represents the equilibrium point at which the outward recoil of the chest wall equals the inward recoil of the lungs.', 1050, 'Physiology'),

-- Renal physiology (medium-hard)
('The glomerular filtration rate (GFR) is normally approximately:', '125 mL/min', '60 mL/min', '1 mL/min', '1 L/min', '125 mL/min', 'Normal GFR in adults is ~125 mL/min (~180 L/day), the vast majority of which is reabsorbed to produce ~1-2 L of urine daily.', 880, 'Physiology'),
('In the proximal convoluted tubule, which substance is reabsorbed with Na+ via co-transport and is normally completely absent from final urine?', 'Glucose', 'Urea', 'Creatinine', 'Phosphate', 'Glucose', 'SGLT2 reabsorbs essentially all filtered glucose with Na+ in the proximal tubule; glucosuria occurs only when plasma glucose exceeds the renal threshold (~180 mg/dL).', 1000, 'Physiology'),
('The countercurrent multiplier in the loop of Henle creates a medullary osmotic gradient by:', 'Active NaCl reabsorption in the thick ascending limb (which is impermeable to water)', 'Active water reabsorption in the descending limb', 'Passive urea secretion in the proximal tubule', 'ADH-driven aquaporin insertion in the ascending limb', 'Active NaCl reabsorption in the thick ascending limb (which is impermeable to water)', 'The thick ascending limb actively pumps NaCl out without water (impermeable), concentrating the medullary interstitium and diluting tubular fluid.', 1700, 'Physiology'),
('Aldosterone promotes Na+ reabsorption primarily in which nephron segment?', 'Cortical collecting duct', 'Proximal convoluted tubule', 'Thick ascending limb of Henle', 'Glomerulus', 'Cortical collecting duct', 'Aldosterone binds intracellular receptors in principal cells of the collecting duct, upregulating ENaC and Na+/K+-ATPase to retain Na+ and excrete K+.', 1350, 'Physiology'),
('Which diuretic class acts by blocking Na+/K+/2Cl- co-transporters in the thick ascending limb?', 'Loop diuretics (e.g., furosemide)', 'Thiazide diuretics', 'Potassium-sparing diuretics', 'Carbonic anhydrase inhibitors', 'Loop diuretics (e.g., furosemide)', 'Loop diuretics inhibit NKCC2 in the thick ascending limb, abolishing the medullary gradient and producing profound diuresis.', 1250, 'Physiology'),

-- Endocrine system & hormones (medium-hard)
('Insulin promotes glucose uptake into skeletal muscle and adipose tissue by stimulating translocation of which transporter to the cell surface?', 'GLUT4', 'GLUT1', 'GLUT2', 'SGLT1', 'GLUT4', 'Insulin receptor activation triggers PI3K/Akt signalling, causing GLUT4-containing vesicles to fuse with the plasma membrane.', 1200, 'Physiology'),
('Parathyroid hormone (PTH) raises plasma calcium by all of the following EXCEPT:', 'Stimulating calcitonin release from the thyroid', 'Stimulating osteoclast activity', 'Increasing renal Ca2+ reabsorption', 'Activating renal 1-alpha-hydroxylase to produce calcitriol', 'Stimulating calcitonin release from the thyroid', 'PTH does not stimulate calcitonin; calcitonin is released from parafollicular C cells in response to hypercalcaemia and opposes PTH.', 1550, 'Physiology'),
('Antidiuretic hormone (ADH/vasopressin) increases water reabsorption in the collecting duct by inserting which channel?', 'Aquaporin-2 (AQP2)', 'Aquaporin-1 (AQP1)', 'ENaC', 'NKCC2', 'Aquaporin-2 (AQP2)', 'ADH binds V2 receptors, activating cAMP-PKA signalling that inserts AQP2 water channels into the luminal membrane of collecting duct cells.', 1300, 'Physiology'),
('Thyroid hormones (T3/T4) increase basal metabolic rate primarily by:', 'Upregulating Na+/K+-ATPase expression, increasing ATP consumption', 'Stimulating glucagon secretion', 'Inhibiting mitochondrial oxidative phosphorylation', 'Decreasing expression of uncoupling proteins', 'Upregulating Na+/K+-ATPase expression, increasing ATP consumption', 'Thyroid hormones increase the number of Na+/K+-ATPase pumps, driving greater ATP turnover and heat production.', 1450, 'Physiology'),
('Which hormone is secreted by the adrenal cortex and is essential for the stress response, promoting gluconeogenesis and suppressing immunity?', 'Cortisol', 'Aldosterone', 'Adrenaline (epinephrine)', 'DHEA', 'Cortisol', 'Cortisol (a glucocorticoid) is released in response to ACTH, stimulates gluconeogenesis in the liver, and inhibits inflammatory pathways.', 920, 'Physiology'),

-- Digestion & absorption (easy-medium)
('Pepsinogen is converted to the active protease pepsin by which factor in the stomach?', 'Low gastric pH (acid)', 'Cholecystokinin', 'Secretin', 'Pancreatic lipase', 'Low gastric pH (acid)', 'Hydrochloric acid secreted by parietal cells lowers gastric pH to 1-2, which cleaves the propeptide to activate pepsinogen to pepsin.', 800, 'Physiology'),
('Fat digestion in the small intestine is facilitated by bile salts, which primarily act by:', 'Emulsifying fat droplets to increase surface area for lipase', 'Directly hydrolysing triglycerides', 'Activating pancreatic lipase allosterically', 'Transporting fatty acids across the enterocyte membrane', 'Emulsifying fat droplets to increase surface area for lipase', 'Bile salts are amphipathic and coat fat globules, forming smaller emulsion droplets with greater surface area accessible to pancreatic lipase.', 950, 'Physiology'),
('Which hormone, released from S cells of the duodenum in response to acid, stimulates pancreatic bicarbonate secretion?', 'Secretin', 'Cholecystokinin', 'Gastrin', 'Ghrelin', 'Secretin', 'Acid entering the duodenum triggers secretin release; secretin acts on pancreatic ductal cells to secrete HCO3-, neutralising chyme.', 1100, 'Physiology'),

-- Acid-base balance (medium-hard)
('In the Henderson-Hasselbalch equation for blood, pH is determined by the ratio of:', '[HCO3-] to dissolved CO2 (alpha x PCO2)', '[Na+] to [Cl-]', '[H+] to [OH-]', '[albumin] to [globulin]', '[HCO3-] to dissolved CO2 (alpha x PCO2)', 'pH = 6.1 + log([HCO3-] / (0.0307 x PCO2)); bicarbonate and PCO2 are the key regulated variables in blood acid-base balance.', 1350, 'Physiology'),
('A patient has pH 7.28, PCO2 55 mmHg, HCO3- 25 mEq/L. What is the primary disorder?', 'Respiratory acidosis', 'Metabolic acidosis', 'Respiratory alkalosis', 'Metabolic alkalosis', 'Respiratory acidosis', 'Elevated PCO2 with normal HCO3- indicates hypoventilation causing CO2 retention; the low pH confirms acidaemia of respiratory origin.', 1500, 'Physiology'),
('In metabolic alkalosis, the kidneys compensate by:', 'Retaining H+ and excreting HCO3-', 'Retaining HCO3- and excreting H+', 'Increasing ventilation to raise PCO2', 'Activating the renin-angiotensin system', 'Retaining H+ and excreting HCO3-', 'The kidney responds to excess HCO3- by reducing H+ secretion and allowing more HCO3- to escape in urine, correcting the alkalosis.', 1650, 'Physiology'),

-- Thermoregulation & homeostasis (easy-medium)
('The primary thermostatic centre that integrates body temperature and coordinates heat loss and heat conservation is located in the:', 'Hypothalamus', 'Cerebral cortex', 'Cerebellum', 'Brainstem reticular formation', 'Hypothalamus', 'The hypothalamus contains warm- and cold-sensitive neurons that compare core temperature to the set point and drive effector responses accordingly.', 820, 'Physiology'),
('Sweating as a mechanism of heat loss relies predominantly on which physical process?', 'Evaporation of water from the skin surface', 'Radiation of infrared energy', 'Convection by air currents', 'Conduction to cooler surfaces', 'Evaporation of water from the skin surface', 'Each gram of sweat evaporated removes ~580 cal of heat; evaporation is the dominant heat-loss mechanism during exercise and in hot environments.', 750, 'Physiology'),
('In a negative feedback homeostatic loop, the effector response:', 'Opposes and corrects the original deviation from the set point', 'Amplifies the original deviation', 'Is triggered only when the set point changes', 'Has no relationship to the sensor signal', 'Opposes and corrects the original deviation from the set point', 'Negative feedback is the cornerstone of homeostasis: the effector reduces the error signal, returning the variable toward its set point.', 700, 'Physiology');
