INSERT INTO statistics (question, answer1, answer2, answer3, answer4, correctanswer, feedback, score, subject) VALUES
-- ── DESCRIPTIVE STATISTICS (easy/medium) ─────────────────────────────────────
('What is the mean of the data set {3, 7, 7, 19}?', '7', '9', '8', '36', '9', 'The mean is the sum (3+7+7+19=36) divided by the count (4), giving 9.', 720, 'Statistics'),
('What is the median of the ordered data set {4, 8, 15, 16, 23}?', '8', '15', '16', '13.2', '15', 'The median is the middle value of an odd-sized sorted list, which is the 3rd element: 15.', 720, 'Statistics'),
('What is the mode of {2, 3, 3, 5, 7, 3, 8}?', '2', '5', '3', '7', '3', 'The mode is the value that appears most frequently; 3 appears three times.', 720, 'Statistics'),
('The variance of {2, 4, 4, 4, 5, 5, 7, 9} is 4. What is the standard deviation?', '16', '2', '8', '4', '2', 'Standard deviation is the square root of the variance: sqrt(4) = 2.', 750, 'Statistics'),
('Which measure of central tendency is most resistant to extreme outliers?', 'Mean', 'Median', 'Range', 'Variance', 'Median', 'The median depends only on the middle ranked value, so outliers have little effect on it.', 780, 'Statistics'),
('For a perfectly symmetric, bell-shaped distribution, which statement is true?', 'Mean > Median > Mode', 'Mean < Median < Mode', 'Mean = Median = Mode', 'Median = 0', 'Mean = Median = Mode', 'In a symmetric unimodal distribution the mean, median, and mode all coincide at the center.', 700, 'Statistics'),
('If every value in a data set is multiplied by a constant k, the standard deviation is multiplied by:', 'k^2', 'sqrt(k)', 'k', '1/k', 'k', 'Multiplying all values by k scales all deviations by k, so sigma is multiplied by |k|.', 950, 'Statistics'),
('The interquartile range (IQR) is defined as:', 'Q3 - Q1', 'Q4 - Q0', 'Q2 - Q1', 'max - min', 'Q3 - Q1', 'IQR = Q3 minus Q1 and measures the spread of the middle 50% of the data.', 720, 'Statistics'),
('A distribution with a long right tail is described as:', 'Negatively skewed', 'Symmetric', 'Positively skewed', 'Bimodal', 'Positively skewed', 'A right (positive) skew means the tail extends toward higher values pulling the mean above the median.', 780, 'Statistics'),
-- ── PROBABILITY RULES (easy/medium) ──────────────────────────────────────────
('Two fair dice are rolled. What is the probability that the sum equals 7?', '1/12', '1/6', '1/9', '7/36', '1/6', 'There are 6 favorable outcomes out of 36 equally likely outcomes, giving 6/36 = 1/6.', 780, 'Statistics'),
('If P(A) = 0.4 and P(B) = 0.5 and A and B are mutually exclusive, what is P(A or B)?', '0.2', '0.9', '0.7', '0.1', '0.9', 'For mutually exclusive events P(A union B) = P(A) + P(B) = 0.4 + 0.5 = 0.9.', 750, 'Statistics'),
('If P(A) = 0.6 and P(B) = 0.5 and P(A and B) = 0.3, what is P(A or B)?', '0.8', '1.1', '0.3', '0.6', '0.8', 'By the addition rule P(A or B) = 0.6 + 0.5 - 0.3 = 0.8.', 780, 'Statistics'),
-- ── CONDITIONAL PROBABILITY & INDEPENDENCE ────────────────────────────────────
('If P(A) = 0.5, P(B) = 0.4, and P(A and B) = 0.2, what is P(A|B)?', '0.4', '0.5', '0.8', '0.2', '0.5', 'P(A|B) = P(A and B) / P(B) = 0.2 / 0.4 = 0.5.', 950, 'Statistics'),
('Events A and B are independent if and only if:', 'P(A and B) = P(A) + P(B)', 'P(A|B) = P(B)', 'P(A and B) = P(A) * P(B)', 'P(A or B) = 0', 'P(A and B) = P(A) * P(B)', 'Independence means the joint probability equals the product of the marginal probabilities.', 950, 'Statistics'),
('A bag has 4 red and 6 blue balls. Two balls are drawn without replacement. What is the probability both are red?', '4/25', '2/15', '12/100', '1/6', '2/15', 'P(both red) = (4/10)*(3/9) = 12/90 = 2/15.', 1100, 'Statistics'),
-- ── BAYES'' THEOREM ───────────────────────────────────────────────────────────
('A disease affects 1% of the population. A test is 95% sensitive and 90% specific. Given a positive test, what is the approximate probability of having the disease?', '95%', '1%', '8.7%', '50%', '8.7%', 'By Bayes'' theorem: P(D|+) = (0.95*0.01)/[(0.95*0.01)+(0.10*0.99)] ≈ 0.087, i.e. about 8.7%.', 1750, 'Statistics'),
('Bayes'' theorem states that P(H|E) equals:', 'P(E|H) / P(H)', 'P(H) * P(E)', 'P(E|H) * P(H) / P(E)', 'P(H|E) * P(E) / P(H)', 'P(E|H) * P(H) / P(E)', 'Bayes'' theorem: P(H|E) = P(E|H)*P(H) / P(E), combining the likelihood, prior, and evidence.', 1350, 'Statistics'),
-- ── COMBINATORICS IN PROBABILITY ─────────────────────────────────────────────
('How many ways can 3 students be chosen from a group of 10?', '30', '120', '720', '10', '120', 'The number of combinations is C(10,3) = 10!/(3!*7!) = 120.', 950, 'Statistics'),
('A committee of 2 men and 2 women is chosen from 5 men and 4 women. How many committees are possible?', '40', '60', '20', '120', '60', 'C(5,2)*C(4,2) = 10*6 = 60 possible committees.', 1100, 'Statistics'),
-- ── DISCRETE DISTRIBUTIONS – BINOMIAL ────────────────────────────────────────
('A fair coin is flipped 6 times. What is the probability of exactly 2 heads?', '15/64', '1/4', '6/64', '1/16', '15/64', 'P(X=2) = C(6,2)*(0.5)^2*(0.5)^4 = 15*(1/64) = 15/64.', 1100, 'Statistics'),
('For a binomial distribution B(n, p), the mean is:', 'n/p', 'n*p*(1-p)', 'np', 'sqrt(np)', 'np', 'The expected value of a binomial random variable is E[X] = np.', 780, 'Statistics'),
('For a binomial distribution B(n, p), the variance is:', 'np', 'np^2', 'np(1-p)', 'n^2*p', 'np(1-p)', 'The variance of a binomial random variable is Var(X) = np(1-p).', 950, 'Statistics'),
('Which condition is NOT required for a binomial distribution?', 'Fixed number of trials', 'Each trial is independent', 'Continuous outcomes', 'Constant probability of success', 'Continuous outcomes', 'Binomial trials must have binary (not continuous) outcomes: success or failure.', 780, 'Statistics'),
-- ── DISCRETE DISTRIBUTIONS – POISSON ─────────────────────────────────────────
('The Poisson distribution with parameter lambda has mean equal to:', 'lambda^2', '1/lambda', 'sqrt(lambda)', 'lambda', 'lambda', 'For a Poisson distribution both the mean and variance equal lambda.', 780, 'Statistics'),
('A call center receives an average of 4 calls per minute. What is the probability of receiving exactly 0 calls in a given minute? (e ≈ 2.718)', 'e^(-4)', '4*e^(-4)', '1 - e^(-4)', '4/e', 'e^(-4)', 'P(X=0) = e^(-4)*4^0/0! = e^(-4) ≈ 0.0183.', 1100, 'Statistics'),
('For a Poisson random variable with lambda = 3, the variance is:', '9', 'sqrt(3)', '6', '3', '3', 'The variance of a Poisson distribution equals its parameter lambda, so Var(X) = 3.', 950, 'Statistics'),
-- ── DISCRETE DISTRIBUTIONS – GEOMETRIC ───────────────────────────────────────
('A geometric distribution models:', 'The number of successes in n trials', 'The number of trials until the first success', 'The number of defects per unit area', 'The waiting time between events', 'The number of trials until the first success', 'The geometric distribution counts trials needed to obtain the first success in Bernoulli trials.', 780, 'Statistics'),
('For a geometric distribution with success probability p, the mean number of trials until the first success is:', 'p', '1-p', '1/p', 'p/(1-p)', '1/p', 'E[X] = 1/p for the geometric distribution counting the trial of first success.', 950, 'Statistics'),
-- ── CONTINUOUS DISTRIBUTIONS – UNIFORM ───────────────────────────────────────
('For a continuous uniform distribution on [a, b], the mean is:', '(b-a)/2', 'a + b', 'b - a', '(a+b)/2', '(a+b)/2', 'The mean of U(a,b) is the midpoint of the interval: (a+b)/2.', 780, 'Statistics'),
('For a continuous uniform distribution on [2, 8], what is the variance?', '1', '3', '36', '6', '3', 'Var(X) = (b-a)^2/12 = (8-2)^2/12 = 36/12 = 3.', 1100, 'Statistics'),
-- ── CONTINUOUS DISTRIBUTIONS – NORMAL ────────────────────────────────────────
('A standard normal distribution has mean mu and standard deviation sigma equal to:', 'mu=1, sigma=0', 'mu=0, sigma=0', 'mu=1, sigma=1', 'mu=0, sigma=1', 'mu=0, sigma=1', 'The standard normal Z ~ N(0,1) has mean 0 and standard deviation 1 by definition.', 700, 'Statistics'),
('If X ~ N(50, 100) (mean=50, variance=100), what is the z-score for X=65?', '0.15', '1.5', '65', '0.65', '1.5', 'z = (X - mu)/sigma = (65 - 50)/10 = 1.5, where sigma = sqrt(100) = 10.', 950, 'Statistics'),
('The empirical rule states that approximately what percentage of data falls within 2 standard deviations of the mean in a normal distribution?', '68%', '99.7%', '95%', '75%', '95%', 'The 68-95-99.7 rule states ~95% of data lies within 2 sigma of the mean.', 750, 'Statistics'),
('Which property is NOT true of the normal distribution?', 'It is symmetric about the mean', 'The total area under the curve equals 1', 'It has a fixed range [0,1]', 'Mean = Median = Mode', 'It has a fixed range [0,1]', 'The normal distribution is defined over all real numbers, not bounded between 0 and 1.', 780, 'Statistics'),
-- ── CONTINUOUS DISTRIBUTIONS – EXPONENTIAL ───────────────────────────────────
('The exponential distribution with rate parameter lambda has mean equal to:', 'lambda', 'lambda^2', '1/lambda', 'sqrt(lambda)', '1/lambda', 'For an exponential distribution the mean (expected value) is 1/lambda.', 780, 'Statistics'),
('The memoryless property is a characteristic of which distribution?', 'Normal', 'Binomial', 'Exponential', 'Uniform', 'Exponential', 'The exponential distribution is the only continuous distribution with the memoryless property.', 1100, 'Statistics'),
-- ── EXPECTATION & VARIANCE ────────────────────────────────────────────────────
('If E[X] = 3 and Var(X) = 4, what is E[2X + 1]?', '7', '10', '9', '8', '7', 'E[2X+1] = 2*E[X]+1 = 2*3+1 = 7 by the linearity of expectation.', 950, 'Statistics'),
('If X and Y are independent, Var(X + Y) equals:', 'Var(X) - Var(Y)', 'Var(X) * Var(Y)', 'Var(X) + Var(Y)', '(Var(X) + Var(Y))^2', 'Var(X) + Var(Y)', 'For independent random variables, variances are additive: Var(X+Y) = Var(X) + Var(Y).', 1100, 'Statistics'),
('If Var(X) = 9, what is Var(3X - 5)?', '27', '72', '81', '9', '81', 'Var(aX + b) = a^2*Var(X), so Var(3X-5) = 9*9 = 81.', 1350, 'Statistics'),
-- ── CENTRAL LIMIT THEOREM & SAMPLING ─────────────────────────────────────────
('The Central Limit Theorem states that for large n, the sample mean X-bar is approximately:', 'Exponentially distributed', 'Chi-squared distributed', 'Normally distributed', 'Uniformly distributed', 'Normally distributed', 'The CLT guarantees that the sampling distribution of X-bar approaches a normal distribution as n increases, regardless of the population distribution.', 950, 'Statistics'),
('According to the CLT, the standard error of the sample mean is:', 'sigma * n', 'sigma / n', 'sigma / sqrt(n)', 'sigma^2 / n', 'sigma / sqrt(n)', 'The standard error (standard deviation of X-bar) is sigma divided by sqrt(n).', 950, 'Statistics'),
-- ── CONFIDENCE INTERVALS ──────────────────────────────────────────────────────
('A 95% confidence interval for mu means:', 'P(mu is in the interval) = 0.95', 'There is a 95% chance mu equals X-bar', 'In repeated sampling, 95% of such intervals will contain mu', 'The interval contains 95% of individual data points', 'In repeated sampling, 95% of such intervals will contain mu', 'A confidence interval is a frequentist statement about the procedure: 95% of CIs constructed this way cover the true parameter.', 1350, 'Statistics'),
('For a large sample with known sigma, a 99% confidence interval for the mean uses z* =', '1.645', '1.96', '2.576', '2.33', '2.576', 'The z-critical value for a two-tailed 99% CI is z* = 2.576, corresponding to 0.5% in each tail.', 1100, 'Statistics'),
-- ── HYPOTHESIS TESTING ────────────────────────────────────────────────────────
('A Type I error occurs when:', 'H0 is true and we fail to reject it', 'H0 is false and we reject it', 'H0 is true and we reject it', 'H0 is false and we fail to reject it', 'H0 is true and we reject it', 'A Type I error (false positive) is rejecting a true null hypothesis; its probability is the significance level alpha.', 1100, 'Statistics'),
('A Type II error occurs when:', 'H0 is false and we reject it', 'H0 is true and we reject it', 'H0 is false and we fail to reject it', 'H0 is true and we fail to reject it', 'H0 is false and we fail to reject it', 'A Type II error (false negative) is failing to reject a false null hypothesis; its probability is denoted beta.', 1100, 'Statistics'),
('If the p-value of a hypothesis test is 0.03 and the significance level is alpha = 0.05, what do you conclude?', 'Fail to reject H0; insufficient evidence', 'Reject H0; statistically significant result', 'Accept H0; the result is conclusive', 'Reject H1; result is not significant', 'Reject H0; statistically significant result', 'Since p-value (0.03) < alpha (0.05), we reject the null hypothesis at the 5% significance level.', 950, 'Statistics'),
('A chi-square test for goodness of fit is used to:', 'Compare two population means', 'Test whether observed frequencies match expected frequencies', 'Estimate the population standard deviation', 'Test whether a distribution is normal only', 'Test whether observed frequencies match expected frequencies', 'The chi-square goodness-of-fit test assesses how well observed counts match a hypothesized distribution.', 1100, 'Statistics'),
-- ── CORRELATION & REGRESSION ──────────────────────────────────────────────────
('A correlation coefficient r = -0.92 indicates:', 'No linear relationship', 'Weak positive linear relationship', 'Strong negative linear relationship', 'Perfect positive linear relationship', 'Strong negative linear relationship', 'r close to -1 indicates a strong negative (inverse) linear relationship between the two variables.', 780, 'Statistics'),
('In simple linear regression y = b0 + b1*x, b1 represents:', 'The y-intercept', 'The predicted value of y when x = 0', 'The change in y for a one-unit increase in x', 'The correlation coefficient', 'The change in y for a one-unit increase in x', 'The slope b1 is the estimated change in the response y for each additional unit of the predictor x.', 950, 'Statistics'),
-- ── MAXIMUM LIKELIHOOD ────────────────────────────────────────────────────────
('The maximum likelihood estimator (MLE) of the mean mu for a normal population N(mu, sigma^2) with a random sample x1,...,xn is:', 'The sample median', 'sigma/sqrt(n)', 'The sample mean x-bar', 'The sample mode', 'The sample mean x-bar', 'Maximizing the normal log-likelihood with respect to mu yields the sample mean as the MLE.', 1600, 'Statistics');
